/*
 * @Description:
 * @Author: Yi Li
 * @Date: 2021-11-17 01:51:26
 * @LastEditors: Mary Qian
 */

export const CommonApi = {
    // Copilot
    PBNA_MOBILE_API_GET_MANAGER_KPI: '',
    PBNA_MOBILE_API_GET_SALES_KPI: '',
    PBNA_MOBILE_API_GET_DEL_SUP_KPI: '',
    PBNA_MOBILE_API_PERFORMANCE: '',
    PBNA_MOBILE_API_PERFORMANCE_DETAIL: '',
    PBNA_MOBILE_API_GET_DEL_SUP_BOX_INFO: '',
    PBNA_MOBILE_API_GET_MERCHANDISE_KPI: '',
    PBNA_MOBILE_API_GET_PERFORMANCE: '',
    PBNA_MOBILE_API_GET_MANAGER_WO: '',
    PBNA_MOBILE_API_DEL_SUP_ADAS_INFO: '',
    PBNA_MOBILE_API_DEL_SUP_MANIFEST: '',
    PBNA_MOBILE_API_DEL_SUP_HOURS: '',
    PBNA_MOBILE_API_DEL_DUP_PERFORMANCE: '',
    PBNA_MOBILE_API_SDL_ASAS_METRICS: '',
    PBNA_MOBILE_API_SDL_ASAS_CLICK_IN: '',
    PBNA_MOBILE_API_SDL_OFF_CLICK_IN: '',
    PBNA_MOBILE_API_SDL_USER_CLICK_IN: '',
    PBNA_MOBILE_API_GET_MM_AMAS: '',

    // Breadcrumbs
    PBNA_MOBILE_API_BREADCRUMBS_BASEURL: '',
    PBNA_MOBILE_API_HISTORICAL_ROUTE: '',
    PBNA_MOBILE_API_BREADCRUMBS_URL: '',
    PBNA_MOBILE_API_LIVE_TRACKING: '',
    PBNA_MOBILE_BREADCRUMB_SWITCH: '',

    // Customer Metrics
    PBNA_MOBILE_API_CUST_METRICS_BASEURL: '',
    PBNA_MOBILE_API_CUSTOMER_METRICS_BRND: '',
    PBNA_MOBILE_API_CUSTOMER_METRICS_INVEN: '',
    PBNA_MOBILE_API_CUSTOMER_METRICS_PKG: '',
    PBNA_MOBILE_API_CUSTOMER_METRICS_TD: '',
    PBNA_MOBILE_API_CUSTOMER_METRICS_CTGRY: '',
    PBNA_MOBILE_API_CUSTOMER_METRICS_TREND: '',
    PBNA_MOBILE_API_CUSTOMER_SALES_TREND: '',
    PBNA_MOBILE_API_CUSTOMER_TREND: '',

    // Customer Invoice
    PBNA_MOBILE_API_CUSTOMER_HEADER: '',
    PBNA_MOBILE_API_CUSTOMER_LINE: '',

    // Rest
    // the interface is called before the values are fetched, need fill value on the front end
    PBNA_MOBILE_API_SSO_LOGIN_CREDENTIAL: 'ssologincredential',
    PBNA_MOBILE_API_USER_PHOTO: '',
    PBNA_MOBILE_API_ASSESSMENT_TASK: '',
    PBNA_MOBILE_API_APEX_REST: '',
    PBNA_MOBILE_API_STATIC_RESOURCE: '',
    PBNA_MOBILE_API_EMPLOYEE_SCHEDULE: '',

    // Copilot Page Link
    PBNA_MOBILE_SCHOOX_SCHEMES: '',
    PBNA_MOBILE_URL_COPILOT_SCHOOX: '',
    PBNA_MOBILE_URL_COPILOT_MYPEPSICO: '',
    PBNA_MOBILE_URL_COPILOT_HELP_DESK: '',
    PBNA_MOBILE_URL_COPILOT_MYIDM: '',
    PBNA_MOBILE_URL_COPILOT_JOB_HURT: '',
    PBNA_MOBILE_URL_COPILOT_EQUIP_SERVICE: '',
    PBNA_MOBILE_NUM_COPILOT_PHONE: '',
    PBNA_MOBILE_NUM_COPILOT_PHONE_TWO: '',
    // Quick Links
    PBNA_MOBILE_URL_PEPSICO_DIRECT: '',
    PBNA_MOBILE_URL_EQUIPMENT_SERVICE: '',
    PBNA_MOBILE_URL_SAVVY_CENTER: '',
    PBNA_MOBILE_NUM_PEPSICO_DIRECT_PHONE: '',
    PBNA_MOBILE_NUM_AR_PHONE_ONE: '',
    PBNA_MOBILE_NUM_AR_PHONE_TWO: '',
    PBNA_MOBILE_NUM_EQUIP_SERVICE_PHONE: '',
    PBNA_MOBILE_NUM_COPILOT_PHONE_THREE: '',
    PBNA_MOBILE_NUM_ACCOMMODATIONS_PHONE: '',

    // Planogram Link
    PBNA_MOBILE_URL_PLANOGRAM_AUTHURL: '',
    PBNA_MOBILE_URL_PLANOGRAM_BEVOPT: '',
    PBNA_MOBILE_URL_PLANOGRAM_POG: '',

    // Breadcrumbs
    PBNA_MOBILE_CONFIG_BC_IN_METERS: '',
    PBNA_MOBILE_CONFIG_BC_OUT_METERS: '',
    PBNA_MOBILE_CONFIG_BC_MAX_NUM: '',
    PBNA_MOBILE_CONFIG_BC_EXPIRE_DATE: '',
    PBNA_MOBILE_CONFIG_BC_UPLOAD_TIME: '',
    PBNA_MOBILE_CONFIG_BC_STILL_TIME: '',
    // Visit Duration
    PBNA_MOBILE_OPEN_VISIT_DURATION: '',
    // PSR My day
    PBNA_MOBILE_PSR_DAY_REFRESH: '',
    // My Visits
    PBNA_MOBILE_API_EVENT_USER_INFO: '',
    PBNA_MOBILE_API_CONNECT_NOTIFICATION: '',
    // UnitUtils
    PBNA_MOBILE_CONFIG_MILE_TO_KM: '',
    PBNA_MOBILE_COUNTRY_CANADA: '',
    // Innovation Product
    PBNA_MOBILE_URL_IP_DAM_ACCESS_TOKEN: '',
    PBNA_MOBILE_URL_IP_DAM_ASSET_DETAILS: '',
    PBNA_MOBILE_URL_IP_DAM_ASSET_P1: '',
    PBNA_MOBILE_URL_IP_DAM_ASSET_P2: '',
    PBNA_MOBILE_URL_IP_DAM_ASSET_P2_1: '',
    PBNA_MOBILE_URL_IP_DAM_ASSET_P2_2: '',
    // Encrypt key
    PBNA_CRYPTOKEY: '',
    // Iv
    PBNA_INITIALIZATION_VECTOR: '',
    // Order Information
    PBNA_MOBILE_URL_ORDER_INFORMATION: '',
    /* restApex url */
    PBNA_MOBILE_RECALCULATE_MEETING_API: '',
    PBNA_MOBILE_RECALCULATE_SCHEDULE_API: '',
    PBNA_MOBILE_PUBLISH_SCHEDULE_API: '',
    PBNA_MOBILE_EVENT_GENERATION_API: '',
    PBNA_MOBILE_CANCEL_SCHEDULE_API: '',
    PBNA_MOBILE_CANCEL_GENERATING_API: '',
    PBNA_MOBILE_VISIT_GENERATION_API: '',
    PBNA_MOBILE_UPDATE_LAST_LOCATION: '',

    /* Notification Key */
    // MERCH
    // VISIT UPDATES
    PBNA_MOBILE_NOT_MERCH_ADHOC_VISIT: '',
    PBNA_MOBILE_RE_SEQUENCE_VISIT: '',
    // DELIVERY UPDATES
    PBNA_MOBILE_NOT_MERCH_SHIPMENT: '',
    PBNA_MOBILE_NOT_MERCH_REMOVE_VISIT: '',

    // MANAGER
    // VISIT UPDATES
    PBNA_MOBILE_NOT_MM_INCOMPLETE_VISIT: '',
    PBNA_MOBILE_NOT_SDL_OFF_SCHEDULE: '',
    // SCHEDULING UPDATES
    PBNA_MOBILE_NOT_MM_ADHOC_VISIT: '',
    PBNA_MOBILE_NOT_MM_SCHEDULE_CHANGE: '',
    // EMPLOYEE UPDATES
    PBNA_MOBILE_NOT_MM_GAP_TIME: '',
    PBNA_MOBILE_NOT_SDL_NO_START: '',
    PBNA_MOBILE_NOT_DELSUP_OVER_HOUR: '',
    PBNA_MOBILE_NOT_DELSUP_GATE_DELAY: '',
    PBNA_MOBILE_NOT_DELSUP_STEM_TIME: '',
    PBNA_MOBILE_NOT_DELSUP_LATE_START: '',
    PBNA_MOBILE_NOT_DELSUP_NO_START: '',

    // Dispatch Report
    PBNA_MOBILE_GET_DISPATCH_REPORT: '',

    // PSR
    PBNA_MOBILE_GET_PRODUCT_PHOTO: '',

    // Dynamic Frequency
    PBNA_MOBILE_GET_DF_FLAG_TOGGLE: '',

    // Sync Service
    PBNA_MOBILE_SYNC_SERVICE: 'mobileSyncService',

    // My Pepsico Base Url
    PBNA_MYPEPSICO_BASE_URL: '',

    // goSpotCheck Api Base Url
    PBNA_MOBILE_API_GO_SPOT_CHECK_BASE_URL: '',

    // scheme url
    PBNA_MOBILE_SAVVY_SCHEME: '',

    // Get SharePoint Token
    PBNA_MOBILE_GET_SHAREPOINT_TOKEN_URL: '',

    // gospotcheck APP scheme URL
    PBNA_MOBILE_GO_SPOT_CHECK_URL: '',

    // gospotcheck APP Store URL
    PBNA_MOBILE_GSP_APP_STORE_URL: '',

    // och api url
    PBNA_OCH_ENDPOINT: '',

    // agreement url
    PBNA_TERMS_AND_CONDITIONS_API: '',

    // SHAREPOINT_DOCUMENT_API
    PBNA_MOBILE_SHAREPOINT_DOCUMENT_API: '',
    PBNA_MOBILE_SHAREPOINT_CONTRACT_API: '',

    // contract pdf file directory
    PBNA_MOBILE_PDF_FILE_DIRECTORY: '',
    PBNA_MOBILE_PDF_POST_CDA_AUDITS: '',
    PBNA_MOBILE_PDF_GENERAL_AUDITS: '',

    // POG api url
    PBNA_POG_ENDPOINT: '',
    PBNA_POG_CSV_ENDPOINT: '',

    // equipment image url
    PBNA_MOBILE_GET_SP_EQ_TOKEN_URL: '',
    PBNA_MOBILE_SHAREPOINT_SITE_BASE_URL: '',
    PBNA_MOBILE_SHAREPOINT_DRIVES_BASE_URL: '',
    PBNA_MOBILE_SHAREPOINT_EQ_IMG_NAME_URL: '',
    PBNA_MOBILE_SHAREPOINT_EQ_PDF_NAME_URL: '',
    PBNA_MOBILE_SHAREPOINT_EQ_SUBTYPE_URL: '',

    // KAM Fetch RetailStore Data API
    PBNA_MOBILE_API_GET_KAM_RETAILSTORE: '',
    PBNA_MOBILE_SHAREPOINT_EQ_PDF_URL: '',
    PBNA_MOBILE_SHAREPOINT_EQ_BRANDING_URL: '',

    // profile
    PBNA_MOBILE_API_CUSTOMER_PRICE_GROUP: '',

    // release note
    PBNA_MOBILE_API_RELEASE_NOTE: '',

    // Sales Support Doc Directory
    PBNA_MOBILE_SALES_DOCUMENTS_DIRECTORY: '',

    // SharePoint Url
    PBNA_MOBILE_FS_SHAREPOINT_TOKEN_URL: '',
    PBNA_MOBILE_SHAREPOINT_BATCH_BASE_URL: '',
    PBNA_MOBILE_SHAREPOINT_REQUEST_URL: '',
    PBNA_SHARE_POINT_PEPSICO_URL: '',
    PBNA_SALES_DOC_PATH_P1: '',
    PBNA_SALES_DOC_PATH_P2: '',
    PBNA_MOBILE_API_PRICE_GROUP_INFO: '',

    // Realogram
    PBNA_MOBILE_API_REALOGRAM_VISIT: '',

    // Present
    PBNA_MOBILE_API_PRESENT_VISIT: '',
    // Mapsted Tweaks Domain
    PBNA_MOBILE_MAPSTED_TWEAKS_DOMAIN: '',
    // Mapsted Tweaks auth Domain
    PBNA_MOBILE_MAPSTED_TWEAKS_AUTH_URL: '',

    PBNA_MOBILE_API_REWARDS_PROGRAMS: '',

    // delivery time window
    PBNA_OMNITRACS_AUTH_URL: '',
    PBNA_OMNITRACS_TIMEWINDOW_URL: '',

    // Feature Toggle Sync
    PBNA_MOBILE_FEATURE_TOGGLE_SYNC: ''
}
