/**
 * @description Page <NewScheduleList> retrieve employee basic data.
 */

import WorkOrderService from '../module/work-order/WorkOrderService'

const EmployeeQuerySelect = `
    SELECT
    {User:Id},
    {User:Name},
    {User:FirstName},
    {User:LastName},
    {User:Phone},
    {User:LC_ID__c},
    {User:GM_LOC_ID__c},
    {User:GPID__c},
    {User:BU_ID__c},
    {User:PERSONA__c},
    {User:Title},
    {User:MobilePhone},
    {User:FT_EMPLYE_FLG_VAL__c},
    {User_Stats__c:Id},
    {User_Stats__c:Schedule_Favorited__c},
    {User_Stats__c:Manager_Directs__c},
    {Visit_List__c:Start_Date_Time__c},
    {Visit_List__c:End_Date_Time__c},
    {Visit_List__c:OwnerId},
    {Visit_List__c:Status__c},
    {Visit_List__c:Visit_Date__c},
    {Visit_List__c:Id},
    {Visit_List__c:IsRemoved__c},
    {Visit_List__c:Total_Planned_Time__c},
    {Visit_List__c:Unscheduled__c},
    {Visit:Planned_Date__c},
    {Visit:Id},
    {Visit:RecordTypeId},
    {Visit:RecordType.DeveloperName},
    {Visit:Visit_List__c},
    {Visit:VisitorId},
    {Visit:PlannedVisitStartTime},
    {Visit:ActualVisitEndTime},
    {Visit:ActualVisitStartTime},
    {Visit:Status__c},
    {Visit:Sequence__c},
    {Visit:Planned_Duration_Minutes__c},
    {Visit:Visit_Subtype__c},
    {Visit:Take_Order_Flag__c},
    {Visit:AMAS_Compliant__c},
    {Visit:Pull_Number__c},
    {Visit:InstructionDescription},
    {Visit:Planned_Mileage__c},
    {Visit:Planned_Travel_Time__c},
    {RetailStore:Id},
    {RetailStore:Street},
    {RetailStore:City},
    {RetailStore:State},
    {RetailStore:Country},
    {RetailStore:PostalCode},
    {RetailStore:Latitude},
    {RetailStore:Longitude},
    {RetailStore:Store_Location__c},
    {RetailStore:Name},
    {Account:Phone},
    {Event:Id},
    {Event:StartDateTime}
    FROM {User} LEFT JOIN {Visit_List__c} ON {User:Id} = {Visit_List__c:OwnerId} 
    AND {User:IsActive} IS TRUE AND {Visit_List__c:IsRemoved__c} IS FALSE
    LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
    LEFT JOIN {Visit} ON {Visit_List__c:Id} = {Visit:Visit_List__c} AND {Visit_List__c:IsRemoved__c} IS NOT TRUE
    AND {Visit:Status__c} != 'Removed' AND {Visit:Status__c} != 'Planned' AND {Visit:Status__c} != 'Failed'
    LEFT JOIN {RetailStore} ON {RetailStore:Id} = {Visit:PlaceId}
    LEFT JOIN {Account} ON {Account:Id} = {RetailStore:AccountId}
    LEFT JOIN {Event} ON {Event:OwnerId} = {User:Id} AND {Event:Manager_Scheduled__c} IS TRUE
`
const EmployeeQueryOrderBy = `
 WHERE {User:GM_LOC_ID__c} = '%s'
 AND {Visit_List__c:Visit_Date__c} = date('%s')
 AND {Visit_List__c:RecordType.DeveloperName} = 'Daily_Visit_List'
 AND (({Visit:RecordType.DeveloperName} = 'Merchandising'
 AND (SELECT count(*) FROM {Visit} WHERE {Visit_List__c:Id} = {Visit:Visit_List__c}) > 0)
 OR (SELECT count(*) FROM {Event} WHERE {Event:OwnerId} = {User:Id} AND {Event:Manager_Scheduled__c} IS TRUE) > 0 
 OR {Visit_List__c:Unscheduled__c} IS TRUE)
 ORDER BY {User:LastName}, {Visit:ActualVisitEndTime} NULLS LAST
`

const VisitAndStoreQuery = `
 SELECT
 {Visit:Id},
 {Visit:Name},
 {Visit:PlaceId},
 {Visit:VisitorId},
 {Visit:Visitor.Name},
 {Visit:Status__c},
 {Visit:ActualVisitEndTime},
 {Visit:ActualVisitStartTime},
 {Visit:LastModifiedDate},
 {Visit:PlannedVisitEndTime},
 {Visit:PlannedVisitStartTime},
 {Visit:Planned_Duration_Minutes__c},
 {Visit:Planned_Travel_Time__c},
 {Visit:Scheduled_Case_Quantity__c},
 {Visit:Planned_Mileage__c},
 {Visit:RecordTypeId},
 {Visit:Visit_List__c},
 {Visit:Planned_Date__c},
 {Visit:Sequence__c},
 {Visit:Pull_Number__c},
 {Visit:OwnerId},
 {Visit:Ad_Hoc__c},
 {Visit:Actual_Duration_Minutes__c},
 {Visit:Schedule_Visit_Group__c},
 {Visit:Route_Group__c},
 {Visit:Dynamic_Frequency_Add__c},
 {Visit:Dynamic_Frequency_Remove__c},
 {RetailStore:Id},
 {RetailStore:Name},
 {RetailStore:Street},
 {RetailStore:City},
 {RetailStore:State},
 {RetailStore:Country},
 {RetailStore:PostalCode},
 {RetailStore:OwnerId},
 {RetailStore:AccountId},
 {RetailStore:Account.Merchandising_Order_Days__c}
 FROM {Visit} JOIN {RetailStore} ON {RetailStore:Id} = {Visit:PlaceId}
`

const VisitAndStoreField = [
    'Id',
    'Name',
    'PlaceId',
    'VisitorId',
    'Visitor.Name',
    'Status__c',
    'ActualVisitEndTime',
    'ActualVisitStartTime',
    'LastModifiedDate',
    'PlannedVisitEndTime',
    'PlannedVisitStartTime',
    'Planned_Duration_Minutes__c',
    'Planned_Travel_Time__c',
    'Scheduled_Case_Quantity__c',
    'Planned_Mileage__c',
    'RecordTypeId',
    'Visit_List__c',
    'Planned_Date__c',
    'Sequence__c',
    'Pull_Number__c',
    'OwnerId',
    'Ad_Hoc__c',
    'Actual_Duration_Minutes__c',
    'Schedule_Visit_Group__c',
    'Route_Group__c',
    'Dynamic_Frequency_Add__c',
    'Dynamic_Frequency_Remove__c',
    'StoreId',
    'StoreName',
    'Street',
    'City',
    'State',
    'Country',
    'PostalCode',
    'SOwnerId',
    'AccountId',
    'OrderDays'
]

const AllVisitQuery = `
    SELECT
    {Visit:Id},
    {Visit:Name},
    {Visit:OwnerId},
    {Visit:PlaceId},
    {Visit:VisitorId},
    {Visit:Status__c},
    {Visit:ActualVisitEndTime},
    {Visit:ActualVisitStartTime},
    {Visit:LastModifiedDate},
    {Visit:PlannedVisitEndTime},
    {Visit:PlannedVisitStartTime},
    {Visit:Ad_Hoc__c},
    {Visit:RecordTypeId},
    {Visit:Planned_Date__c},
    {Visit:Sequence__c},
    {Visit:Pull_Number__c},
    {Visit:Planned_Travel_Time__c},
    {Visit:Scheduled_Case_Quantity__c},
    {Visit:Planned_Mileage__c},
    {Visit:Planned_Duration_Minutes__c},
    {Visit:Actual_Duration_Minutes__c},
    {Visit:Schedule_Visit_Group__c},
    {Visit:Visit_List__c},
    {Visit:Visit_Subtype__c},
    {Visit:Take_Order_Flag__c},
    {Visit:InstructionDescription},
    {Visit:Manager_Ad_Hoc__c},
    {Visit:Sales_Visit__c},
    {Visit:Route_Group__c},
    {Visit:Reassigned_Flag__c},
    {Visit:Dynamic_Frequency_Add__c},
    {Visit:Dynamic_Frequency_Remove__c},
    {Visit:Reassigned__c},
    {Visit:_soupEntryId},
    {Visit:__local__},
    {Visit:__locally_created__},
    {Visit:__locally_updated__},
    {Visit:__locally_deleted__}
    FROM {Visit}
`

const AllVisitField = [
    'Id',
    'Name',
    'OwnerId',
    'PlaceId',
    'VisitorId',
    'Status__c',
    'ActualVisitEndTime',
    'ActualVisitStartTime',
    'LastModifiedDate',
    'PlannedVisitEndTime',
    'PlannedVisitStartTime',
    'Ad_Hoc__c',
    'RecordTypeId',
    'Planned_Date__c',
    'Sequence__c',
    'Pull_Number__c',
    'Planned_Travel_Time__c',
    'Scheduled_Case_Quantity__c',
    'Planned_Mileage__c',
    'Planned_Duration_Minutes__c',
    'Actual_Duration_Minutes__c',
    'Schedule_Visit_Group__c',
    'Visit_List__c',
    'Visit_Subtype__c',
    'Take_Order_Flag__c',
    'InstructionDescription',
    'Manager_Ad_Hoc__c',
    'Sales_Visit__c',
    'Route_Group__c',
    'Reassigned_Flag__c',
    'Dynamic_Frequency_Add__c',
    'Dynamic_Frequency_Remove__c',
    'Reassigned__c'
]
// Be careful!!! When Adding new field up here, need to add it to VisitDetailsField and VisitDetailsQuery too
// BTW, please inform Team1 to add new field too

const VisitDetailsQuery = `
    SELECT
    {Visit:Id},
    {Visit:Name},
    {Visit:OwnerId},
    {Visit:PlaceId},
    {Visit:VisitorId},
    {Visit:Status__c},
    {Visit:ActualVisitEndTime},
    {Visit:ActualVisitStartTime},
    {Visit:LastModifiedDate},
    {Visit:PlannedVisitEndTime},
    {Visit:PlannedVisitStartTime},
    {Visit:Ad_Hoc__c},
    {Visit:RecordTypeId},
    {Visit:Planned_Date__c},
    {Visit:Sequence__c},
    {Visit:Pull_Number__c},
    {Visit:Planned_Travel_Time__c},
    {Visit:Scheduled_Case_Quantity__c},
    {Visit:Planned_Mileage__c},
    {Visit:Planned_Duration_Minutes__c},
    {Visit:Actual_Duration_Minutes__c},
    {Visit:Schedule_Visit_Group__c},
    {Visit:Visit_List__c},
    {Visit:Visit_Subtype__c},
    {Visit:Take_Order_Flag__c},
    {Visit:InstructionDescription},
    {Visit:Manager_Ad_Hoc__c},
    {Visit:Sales_Visit__c},
    {Visit:Route_Group__c},
    {Visit:Reassigned_Flag__c},
    {Visit:Dynamic_Frequency_Add__c},
    {Visit:Dynamic_Frequency_Remove__c},
    {Visit:Reassigned__c},
    {RetailStore:Id},
    {RetailStore:Store_Location__c},
    {RetailStore:Street},
    {RetailStore:City},
    {RetailStore:State},
    {RetailStore:Country},
    {RetailStore:PostalCode},
    {Account:Id},
    {Account:Name},
    {Account:Phone},
    {Account:ShippingAddress},
    {User:Id},
    {User:Name},
    {User:FirstName},
    {User:LastName},
    {User:Title},
    {User:MobilePhone},
    {User:FT_EMPLYE_FLG_VAL__c},
    {User_Stats__c:Id},
    {User_Stats__c:Start_Time__c},
    {User_Stats__c:Sunday__c},
    {User_Stats__c:Monday__c},
    {User_Stats__c:Tuesday__c},
    {User_Stats__c:Wednesday__c},
    {User_Stats__c:Thursday__c},
    {User_Stats__c:Friday__c},
    {User_Stats__c:Saturday__c},
    {User_Stats__c:Merchandising_Base__c}
    FROM {Visit}
    JOIN {RetailStore} ON {Visit:PlaceId} = {RetailStore:Id}
    LEFT JOIN {Account} ON {Account:Id} = {RetailStore:AccountId}
    LEFT JOIN {User} ON {Visit:VisitorId} = {User:Id}
    LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
    WHERE {Visit:Id} = '%s'
`

const VisitDetailsField = AllVisitField.concat([
    'RetailStoreId',
    'Store_Location__c',
    'Street',
    'City',
    'State',
    'Country',
    'PostalCode',
    'AccountId',
    'AccountName',
    'AccountPhone',
    'AccountShippingAddress',
    'UserId',
    'UserName',
    'FirstName',
    'LastName',
    'Title',
    'MobilePhone',
    'FT_EMPLYE_FLG_VAL__c',
    'UserStatsId',
    'Start_Time__c',
    'Sunday__c',
    'Monday__c',
    'Tuesday__c',
    'Wednesday__c',
    'Thursday__c',
    'Friday__c',
    'Saturday__c',
    'Merchandising_Base__c'
])

const AllVisitListQuery = `
    SELECT
    {Visit_List__c:Id},
    {Visit_List__c:Name},
    {Visit_List__c:OwnerId},
    {Visit_List__c:LastModifiedDate},
    {Visit_List__c:Start_Date__c},
    {Visit_List__c:End_Date__c},
    {Visit_List__c:Start_Date_Time__c},
    {Visit_List__c:End_Date_Time__c},
    {Visit_List__c:Visit_Date__c},
    {Visit_List__c:RecordTypeId},
    {Visit_List__c:Status__c},
    {Visit_List__c:Visit_List_Group__c},
    {Visit_List__c:Location_Id__c},
    {Visit_List__c:Updated__c},
    {Visit_List__c:Manager_Ad_Hoc__c},
    {Visit_List__c:Total_Planned_Time__c},
    {Visit_List__c:IsRemoved__c},
    {Visit_List__c:Resequenced__c},
    {Visit_List__c:_soupEntryId},
    {Visit_List__c:__local__},
    {Visit_List__c:__locally_created__},
    {Visit_List__c:__locally_updated__},
    {Visit_List__c:__locally_deleted__}
    FROM {Visit_List__c}
`

const AllVisitListField = [
    'Id',
    'Name',
    'OwnerId',
    'LastModifiedDate',
    'Start_Date__c',
    'End_Date__c',
    'Start_Date_Time__c',
    'End_Date_Time__c',
    'Visit_Date__c',
    'RecordTypeId',
    'Status__c',
    'Visit_List_Group__c',
    'Location_Id__c',
    'Updated__c',
    'Manager_Ad_Hoc__c',
    'Total_Planned_Time__c',
    'IsRemoved__c',
    'Resequenced__c'
]

const AllUserField = [
    'Id',
    'Name',
    'FirstName',
    'LastName',
    'Profile.Name',
    'Phone',
    'GM_LOC_ID__c',
    'GM_LOC_NM__c',
    'PERSONA__c',
    'GPID__c',
    'IsActive',
    'Title',
    'FT_EMPLYE_FLG_VAL__c',
    'USER_ACTIVE__c',
    'ProfileId',
    'Merchandising_Base_Minimum_Requirement__c'
]

const AllUserQuery = `
     SELECT
     {User:Id},
     {User:Name},
     {User:FirstName},
     {User:LastName},
     {User:Profile.Name},
     {User:Phone},
     {User:GM_LOC_ID__c},
     {User:GM_LOC_NM__c},
     {User:PERSONA__c},
     {User:GPID__c},
     {User:IsActive},
     {User:Title},
     {User:FT_EMPLYE_FLG_VAL__c},
     {User:USER_ACTIVE__c},
     {User:ProfileId},
     {User:Merchandising_Base_Minimum_Requirement__c},
     {User:_soupEntryId},
     {User:__local__},
     {User:__locally_created__},
     {User:__locally_updated__},
     {User:__locally_deleted__}
     FROM {User} WHERE {User:Id} = '%s'
 `

const RNSEmployeeField = [
    'Id',
    'OwnerId',
    'VisitorId',
    'Status__c',
    'Planned_Date__c',
    'Planned_Duration_Minutes__c',
    'Sales_Visit__c',
    'Sequence__c',
    'Pull_Number__c',
    'Planned_Travel_Time__c',
    'Scheduled_Case_Quantity__c',
    'Planned_Mileage__c',
    'Visit_Subtype__c',
    'Take_Order_Flag__c',
    'InstructionDescription',
    'Manager_Ad_Hoc__c',
    'Route_Group__c',
    'Dynamic_Frequency_Add__c',
    'DVisitListId',
    'DOwnerId',
    'DVisit_Date__c',
    'DRecordTypeId',
    'DVisit_List_Group__c',
    'Total_Planned_Time__c',
    'DPlanned_Travel_Time__c',
    'WVisitListId',
    'WStart_Date__c',
    'WEnd_Date__c',
    'WOwnerId',
    'WVisit_Date__c',
    'WRecordTypeId',
    'UserId',
    'Username',
    'FirstName',
    'LastName',
    'LocationId',
    'GPID',
    'Title',
    'MobilePhone',
    'FT_EMPLYE_FLG_VAL__c',
    'LC_ID__c',
    'StoreId',
    'StoreName',
    'Street',
    'City',
    'State',
    'Country',
    'PostalCode',
    'SOwnerId',
    'AccountPhone',
    'AccountName',
    'ShippingAddress',
    'Latitude',
    'Longitude',
    'Store_Location__c',
    'UserStatsId',
    'User__c',
    'Start_Time__c',
    'Sunday__c',
    'Monday__c',
    'Tuesday__c',
    'Wednesday__c',
    'Thursday__c',
    'Friday__c',
    'Saturday__c'
]

const RNSEmployeeQuery = `
 SELECT
     {Visit:Id},
     {Visit:OwnerId},
     {Visit:VisitorId},
     {Visit:Status__c},
     {Visit:Planned_Date__c},
     {Visit:Planned_Duration_Minutes__c},
     {Visit:Sales_Visit__c},
     {Visit:Sequence__c},
     {Visit:Pull_Number__c},
     {Visit:Planned_Travel_Time__c},
     {Visit:Scheduled_Case_Quantity__c},
     {Visit:Planned_Mileage__c},
     {Visit:Visit_Subtype__c},
     {Visit:Take_Order_Flag__c},
     {Visit:InstructionDescription},
     {Visit:Manager_Ad_Hoc__c},
     {Visit:Route_Group__c},
     {Visit:Dynamic_Frequency_Add__c},
     DVL.{Visit_List__c:Id},
     DVL.{Visit_List__c:OwnerId},
     DVL.{Visit_List__c:Visit_Date__c},
     DVL.{Visit_List__c:RecordTypeId},
     DVL.{Visit_List__c:Visit_List_Group__c},
     DVL.{Visit_List__c:Total_Planned_Time__c},
     DVL.{Visit_List__c:Planned_Travel_Time__c},
     WVL.{Visit_List__c:Id},
     WVL.{Visit_List__c:Start_Date__c},
     WVL.{Visit_List__c:End_Date__c},
     WVL.{Visit_List__c:OwnerId},
     WVL.{Visit_List__c:Visit_Date__c},
     WVL.{Visit_List__c:RecordTypeId},
     {User:Id},
     {User:Name},
     {User:FirstName},
     {User:LastName},
     {User:GM_LOC_ID__c},
     {User:GPID__c},
     {User:Title},
     {User:MobilePhone},
     {User:FT_EMPLYE_FLG_VAL__c},
     {User:LC_ID__c},
     {RetailStore:Id},
     {RetailStore:Name},
     {RetailStore:Street},
     {RetailStore:City},
     {RetailStore:State},
     {RetailStore:Country},
     {RetailStore:PostalCode},
     {RetailStore:OwnerId},
     {RetailStore:Account.Phone},
     {RetailStore:Account.Name},
     {RetailStore:Account.ShippingAddress},
     {RetailStore:Latitude},
     {RetailStore:Longitude},
     {RetailStore:Store_Location__c},
     {User_Stats__c:Id},
     {User_Stats__c:User__c},
     {User_Stats__c:Start_Time__c},
     {User_Stats__c:Sunday__c},
     {User_Stats__c:Monday__c},
     {User_Stats__c:Tuesday__c},
     {User_Stats__c:Wednesday__c},
     {User_Stats__c:Thursday__c},
     {User_Stats__c:Friday__c},
     {User_Stats__c:Saturday__c}
     FROM {Visit} 
     LEFT JOIN {Visit_List__c} DVL ON DVL.{Visit_List__c:Id} = {Visit:Visit_List__c}
     LEFT JOIN {Visit_List__c} WVL ON WVL.{Visit_List__c:Id} = DVL.{Visit_List__c:Visit_List_Group__c} 
     LEFT JOIN {User} ON {Visit:VisitorId} = {User:Id}
     JOIN {RetailStore} ON {RetailStore:Id} = {Visit:PlaceId}
     LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
     WHERE {Visit:Schedule_Visit_Group__c} = '%s'
     AND {Visit:Status__c} != 'Removed' AND {Visit:Status__c} = 'Planned' AND {Visit:Status__c} != 'Failed'
     AND ({Visit:Route_Group__c} IS NULL AND {Visit:VisitorId} IS NOT NULL
     AND (DVL.{Visit_List__c:IsRemoved__c} IS NOT TRUE AND DVL.{Visit_List__c:RecordType.DeveloperName} = 'Daily_Visit_List'
     AND WVL.{Visit_List__c:IsRemoved__c} IS NOT TRUE) 
     %s
     OR {Visit:Route_Group__c} IS NOT NULL)
     GROUP BY {Visit:Id}
     ORDER BY {User:Id}, {Visit:Sequence__c} NULLS LAST
`

export const OptimizedVisitMetricQuery = (type: 'add' | 'remove', visitListId) => {
    let status, field
    if (type === 'add') {
        status = 'Planned'
        field = 'Dynamic_Frequency_Add__c'
    }
    if (type === 'remove') {
        status = 'Removed'
        field = 'Dynamic_Frequency_Remove__c'
    }
    return [
        `
        SELECT
            VST.{Visit:Id},
            VST.{Visit:Status__c},
            VST.{Visit:Planned_Duration_Minutes__c},
            VST.{Visit:Planned_Travel_Time__c},
            VST.{Visit:Planned_Date__c},
            RS.{RetailStore:Account.CUST_UNIQ_ID_VAL__c},
            RS.{RetailStore:Account.Name},
            USER.{User:BS_PAY_RT_AMT__c} as payRateHourly
        FROM {Visit} VST
        LEFT JOIN {User} USER ON VST.{Visit:VisitorId} = USER.{User:Id}
        LEFT JOIN {RetailStore} RS ON RS.{RetailStore:Id} = VST.{Visit:PlaceId}  
        WHERE VST.{Visit:Schedule_Visit_Group__c} = '${visitListId}'
        AND VST.{Visit:Status__c} = '${status}'
        AND VST.{Visit:${field}} IS TRUE
        `,
        [
            'id',
            'Status__c',
            'Planned_Duration_Minutes__c',
            'Planned_Travel_Time__c',
            'Planned_Date__c',
            'COF',
            'accountName',
            'payRateHourly'
        ]
    ]
}

const RNSOptimizedCustomerQuery = `
SELECT
    {Visit:Id},
    {Visit:VisitorId},
    {Visit:Status__c},
    {Visit:Planned_Date__c},
    {Visit:Planned_Duration_Minutes__c},
    {Visit:Sequence__c},
    {Visit:Pull_Number__c},
    {Visit:Planned_Travel_Time__c},
    {Visit:Scheduled_Case_Quantity__c},
    {Visit:Planned_Mileage__c},
    {Visit:Visit_Subtype__c},
    {Visit:Take_Order_Flag__c},
    {Visit:InstructionDescription},
    {Visit:Manager_Ad_Hoc__c},
    {Visit:Route_Group__c},
    {Visit:Dynamic_Frequency_Add__c},
    {Visit:Dynamic_Frequency_Remove__c},
    DVL.{Visit_List__c:Id},
    DVL.{Visit_List__c:OwnerId},
    DVL.{Visit_List__c:Visit_Date__c},
    DVL.{Visit_List__c:RecordTypeId},
    DVL.{Visit_List__c:Visit_List_Group__c},
    DVL.{Visit_List__c:Planned_Cost__c},
    WVL.{Visit_List__c:Id},
    WVL.{Visit_List__c:Start_Date__c},
    WVL.{Visit_List__c:End_Date__c},
    WVL.{Visit_List__c:OwnerId},
    WVL.{Visit_List__c:Visit_Date__c},
    WVL.{Visit_List__c:RecordTypeId},
    {User:Id},
    {User:Name},
    {User:FirstName},
    {User:LastName},
    {User:GM_LOC_ID__c},
    {User:Title},
    {User:MobilePhone},
    {User:FT_EMPLYE_FLG_VAL__c},
    {User:BS_PAY_RT_AMT__c},
    {RetailStore:Id},
    {RetailStore:Name},
    {RetailStore:Street},
    {RetailStore:City},
    {RetailStore:State},
    {RetailStore:Country},
    {RetailStore:PostalCode},
    {RetailStore:OwnerId},
    {RetailStore:RTLR_STOR_NUM__c},
    {RetailStore:Account.CUST_UNIQ_ID_VAL__c},
    {RetailStore:Account.BUSN_SGMNTTN_LVL_3_NM__c},
    {RetailStore:Account.Phone},
    {RetailStore:Account.Name},
    {RetailStore:Account.ShippingAddress},
    {RetailStore:Account.Sales_Rep_Info__c},
    {RetailStore:Account.Sales_Rep__c},
    {RetailStore:Latitude},
    {RetailStore:Longitude},
    {RetailStore:Store_Location__c},
    RSG.{Route_Sales_Geo__c:LOCL_RTE_ID__c},
    RSG.{Route_Sales_Geo__c:GTMU_RTE_ID__c},
    UUS.{User_Stats__c:Id},
    UUS.{User_Stats__c:User__c},
    UUS.{User_Stats__c:Start_Time__c},
    UUS.{User_Stats__c:Sunday__c},
    UUS.{User_Stats__c:Monday__c},
    UUS.{User_Stats__c:Tuesday__c},
    UUS.{User_Stats__c:Wednesday__c},
    UUS.{User_Stats__c:Thursday__c},
    UUS.{User_Stats__c:Friday__c},
    UUS.{User_Stats__c:Saturday__c},
    RUS.{User_Stats__c:Id}
    FROM {RetailStore} 
    LEFT JOIN {Visit} ON {RetailStore:Id} = {Visit:PlaceId}  
    LEFT JOIN {Route_Sales_Geo__c} RSG ON {RetailStore:Account.Sales_Route__c} = RSG.{Route_Sales_Geo__c:Id} 
    LEFT JOIN {Visit_List__c} DVL ON DVL.{Visit_List__c:Id} = {Visit:Visit_List__c} 
    LEFT JOIN {Visit_List__c} WVL ON WVL.{Visit_List__c:Id} = DVL.{Visit_List__c:Visit_List_Group__c} 
    LEFT JOIN {User} ON {Visit:VisitorId} = {User:Id}
    LEFT JOIN {User_Stats__c} UUS ON UUS.{User_Stats__c:User__c} = {User:Id} 
    LEFT JOIN {User_Stats__c} RUS ON RUS.{User_Stats__c:User__c} = {RetailStore:Account.Sales_Rep__c}
    WHERE {Visit:Schedule_Visit_Group__c} = '%s'
    AND ({Visit:Status__c} = 'Planned' OR {Visit:Status__c} = 'Removed' OR ({Visit:VisitorId} IS NULL AND {Visit:Status__c} != 'Removed' AND {Visit:Status__c} != 'Failed'))
    AND (DVL.{Visit_List__c:IsRemoved__c} IS NOT TRUE 
    AND DVL.{Visit_List__c:RecordType.DeveloperName} = 'Daily_Visit_List' OR DVL.{Visit_List__c:Id} IS NULL) 
    AND (WVL.{Visit_List__c:IsRemoved__c} IS NOT TRUE OR WVL.{Visit_List__c:Id} IS NULL)
    GROUP BY {Visit:Id}
    ORDER BY {RetailStore:Id}, {Visit:Planned_Date__c}, {Visit:Pull_Number__c} NULLS LAST
`

const RNSCustomerField = [
    'Id',
    'VisitorId',
    'Status__c',
    'Planned_Date__c',
    'Planned_Duration_Minutes__c',
    'Sequence__c',
    'Pull_Number__c',
    'Planned_Travel_Time__c',
    'Scheduled_Case_Quantity__c',
    'Planned_Mileage__c',
    'Visit_Subtype__c',
    'Take_Order_Flag__c',
    'InstructionDescription',
    'Manager_Ad_Hoc__c',
    'Route_Group__c',
    'Dynamic_Frequency_Add__c',
    'Dynamic_Frequency_Remove__c',
    'DVisitListId',
    'DOwnerId',
    'DVisit_Date__c',
    'DRecordTypeId',
    'DVisit_List_Group__c',
    'DPlanned_Cost__c',
    'WVisitListId',
    'WStart_Date__c',
    'WEnd_Date__c',
    'WOwnerId',
    'WVisit_Date__c',
    'WRecordTypeId',
    'UserId',
    'Username',
    'FirstName',
    'LastName',
    'LocationId',
    'Title',
    'MobilePhone',
    'FT_EMPLYE_FLG_VAL__c',
    'payRateHourly',
    'StoreId',
    'StoreName',
    'Street',
    'City',
    'State',
    'Country',
    'PostalCode',
    'OwnerId',
    'StoreNumber',
    'COF',
    'busnLvl3',
    'AccountPhone',
    'AccountName',
    'ShippingAddress',
    'Sales_Rep_Info',
    'Sales_Rep__c',
    'Latitude',
    'Longitude',
    'Store_Location__c',
    'LOCL_RTE_ID__c',
    'GTMU_RTE_ID__c',
    'UserStatsId',
    'User__c',
    'Start_Time__c',
    'Sunday__c',
    'Monday__c',
    'Tuesday__c',
    'Wednesday__c',
    'Thursday__c',
    'Friday__c',
    'Saturday__c',
    'SalesRepUserStatsID'
]

const RNSCustomerQuery = `
 SELECT
     {Visit:Id},
     {Visit:VisitorId},
     {Visit:Status__c},
     {Visit:Planned_Date__c},
     {Visit:Planned_Duration_Minutes__c},
     {Visit:Sequence__c},
     {Visit:Pull_Number__c},
     {Visit:Planned_Travel_Time__c},
     {Visit:Scheduled_Case_Quantity__c},
     {Visit:Planned_Mileage__c},
     {Visit:Visit_Subtype__c},
     {Visit:Take_Order_Flag__c},
     {Visit:InstructionDescription},
     {Visit:Manager_Ad_Hoc__c},
     {Visit:Route_Group__c},
     {Visit:Dynamic_Frequency_Add__c},
     {Visit:Dynamic_Frequency_Remove__c},
     DVL.{Visit_List__c:Id},
     DVL.{Visit_List__c:OwnerId},
     DVL.{Visit_List__c:Visit_Date__c},
     DVL.{Visit_List__c:RecordTypeId},
     DVL.{Visit_List__c:Visit_List_Group__c},
     DVL.{Visit_List__c:Planned_Cost__c},
     WVL.{Visit_List__c:Id},
     WVL.{Visit_List__c:Start_Date__c},
     WVL.{Visit_List__c:End_Date__c},
     WVL.{Visit_List__c:OwnerId},
     WVL.{Visit_List__c:Visit_Date__c},
     WVL.{Visit_List__c:RecordTypeId},
     {User:Id},
     {User:Name},
     {User:FirstName},
     {User:LastName},
     {User:GM_LOC_ID__c},
     {User:Title},
     {User:MobilePhone},
     {User:FT_EMPLYE_FLG_VAL__c},
     {User:BS_PAY_RT_AMT__c},
     {RetailStore:Id},
     {RetailStore:Name},
     {RetailStore:Street},
     {RetailStore:City},
     {RetailStore:State},
     {RetailStore:Country},
     {RetailStore:PostalCode},
     {RetailStore:OwnerId},
     {RetailStore:RTLR_STOR_NUM__c},
     {RetailStore:Account.CUST_UNIQ_ID_VAL__c},
     {RetailStore:Account.BUSN_SGMNTTN_LVL_3_NM__c},
     {RetailStore:Account.Phone},
     {RetailStore:Account.Name},
     {RetailStore:Account.ShippingAddress},
     {RetailStore:Account.Sales_Rep_Info__c},
     {RetailStore:Account.Sales_Rep__c},
     {RetailStore:Latitude},
     {RetailStore:Longitude},
     {RetailStore:Store_Location__c},
     RSG.{Route_Sales_Geo__c:LOCL_RTE_ID__c},
     RSG.{Route_Sales_Geo__c:GTMU_RTE_ID__c},
     UUS.{User_Stats__c:Id},
     UUS.{User_Stats__c:User__c},
     UUS.{User_Stats__c:Start_Time__c},
     UUS.{User_Stats__c:Sunday__c},
     UUS.{User_Stats__c:Monday__c},
     UUS.{User_Stats__c:Tuesday__c},
     UUS.{User_Stats__c:Wednesday__c},
     UUS.{User_Stats__c:Thursday__c},
     UUS.{User_Stats__c:Friday__c},
     UUS.{User_Stats__c:Saturday__c},
     RUS.{User_Stats__c:Id}
     FROM {RetailStore} 
     LEFT JOIN {Visit} ON {RetailStore:Id} = {Visit:PlaceId}  
     LEFT JOIN {Route_Sales_Geo__c} RSG ON {RetailStore:Account.Sales_Route__c} = RSG.{Route_Sales_Geo__c:Id} 
     LEFT JOIN {Visit_List__c} DVL ON DVL.{Visit_List__c:Id} = {Visit:Visit_List__c} 
     LEFT JOIN {Visit_List__c} WVL ON WVL.{Visit_List__c:Id} = DVL.{Visit_List__c:Visit_List_Group__c} 
     LEFT JOIN {User} ON {Visit:VisitorId} = {User:Id}
     LEFT JOIN {User_Stats__c} UUS ON UUS.{User_Stats__c:User__c} = {User:Id} 
     LEFT JOIN {User_Stats__c} RUS ON RUS.{User_Stats__c:User__c} = {RetailStore:Account.Sales_Rep__c}
     WHERE {Visit:Schedule_Visit_Group__c} = '%s'
     AND ({Visit:Status__c} = 'Planned' OR ({Visit:VisitorId} IS NULL AND {Visit:Status__c} != 'Removed' AND {Visit:Status__c} != 'Failed'))
     AND (DVL.{Visit_List__c:IsRemoved__c} IS NOT TRUE 
     AND DVL.{Visit_List__c:RecordType.DeveloperName} = 'Daily_Visit_List' OR DVL.{Visit_List__c:Id} IS NULL) 
     AND (WVL.{Visit_List__c:IsRemoved__c} IS NOT TRUE OR WVL.{Visit_List__c:Id} IS NULL)
     GROUP BY {Visit:Id}
     ORDER BY {RetailStore:Id}, {Visit:Planned_Date__c}, {Visit:Pull_Number__c} NULLS LAST
 `

const RNSEmployeeAssignListField = [
    'UserId',
    'Username',
    'FirstName',
    'LastName',
    'LocationId',
    'IsActive',
    'GPID',
    'UserStatsId',
    'Sunday__c',
    'Monday__c',
    'Tuesday__c',
    'Wednesday__c',
    'Thursday__c',
    'Friday__c',
    'Saturday__c',
    'Title',
    'FT_EMPLYE_FLG_VAL__c',
    'Id',
    'OwnerId',
    'VisitorId',
    'Status__c',
    'Planned_Date__c',
    'Planned_Duration_Minutes__c',
    'Planned_Travel_Time__c',
    'Sequence__c',
    'Pull_Number__c',
    'DVisitListId',
    'DOwnerId',
    'DVisit_Date__c',
    'DRecordTypeId',
    'DVisit_List_Group__c',
    'WVisitListId',
    'WStart_Date__c',
    'WEnd_Date__c',
    'WOwnerId',
    'WVisit_Date__c',
    'WRecordTypeId',
    'StoreId',
    'StoreName',
    'Street',
    'City',
    'State',
    'Country',
    'PostalCode',
    'SOwnerId'
]

const RNSEmployeeAssignListQuery = `
        SELECT
            {User:Id},
            {User:Name},
            {User:FirstName},
            {User:LastName},
            {User:GM_LOC_ID__c},
            {User:IsActive},
            {User:GPID__c},
            {User_Stats__c:Id},
            {User_Stats__c:Sunday__c},
            {User_Stats__c:Monday__c},
            {User_Stats__c:Tuesday__c},
            {User_Stats__c:Wednesday__c},
            {User_Stats__c:Thursday__c},
            {User_Stats__c:Friday__c},
            {User_Stats__c:Saturday__c},
            {User:Title},
            {User:FT_EMPLYE_FLG_VAL__c},
            {Visit:Id},
            {Visit:OwnerId},
            {Visit:VisitorId},
            {Visit:Status__c},
            {Visit:Planned_Date__c},
            {Visit:Planned_Duration_Minutes__c},
            {Visit:Planned_Travel_Time__c},
            {Visit:Sequence__c},
            {Visit:Pull_Number__c},
            DVL.{Visit_List__c:Id},
            DVL.{Visit_List__c:OwnerId},
            DVL.{Visit_List__c:Visit_Date__c},
            DVL.{Visit_List__c:RecordTypeId},
            DVL.{Visit_List__c:Visit_List_Group__c},
            WVL.{Visit_List__c:Id},
            WVL.{Visit_List__c:Start_Date__c},
            WVL.{Visit_List__c:End_Date__c},
            WVL.{Visit_List__c:OwnerId},
            WVL.{Visit_List__c:Visit_Date__c},
            WVL.{Visit_List__c:RecordTypeId},
            {RetailStore:Id},
            {RetailStore:Name},
            {RetailStore:Street},
            {RetailStore:City},
            {RetailStore:State},
            {RetailStore:Country},
            {RetailStore:PostalCode},
            {RetailStore:OwnerId}
            FROM {User} LEFT JOIN {Visit} ON {User:Id} = {Visit:VisitorId} AND ({Visit:Schedule_Visit_Group__c} = '%s' OR {Visit:Id} IS NULL)
            LEFT JOIN {Visit_List__c} DVL ON DVL.{Visit_List__c:Id} = {Visit:Visit_List__c} 
            LEFT JOIN {Visit_List__c} WVL ON WVL.{Visit_List__c:Id} = DVL.{Visit_List__c:Visit_List_Group__c} 
            LEFT JOIN {RetailStore} ON {RetailStore:Id} = {Visit:PlaceId}
            LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
            WHERE {User:GM_LOC_ID__c} = '%s' AND {User:IsActive} IS TRUE
            AND ({User:Profile.Name} = 'Frontline' 
            OR {User:Profile.Name} = 'Manager')
            %s
            AND (DVL.{Visit_List__c:IsRemoved__c} IS NOT TRUE AND DVL.{Visit_List__c:RecordType.DeveloperName} = 'Daily_Visit_List'
            OR DVL.{Visit_List__c:Id} IS NULL)
            AND (WVL.{Visit_List__c:IsRemoved__c} IS NOT TRUE OR WVL.{Visit_List__c:Id} IS NULL)
            ORDER BY {User:LastName}
        `
const MyTeamListField = [
    'UserId',
    'Username',
    'FirstName',
    'LastName',
    'Title',
    'LocationId',
    'MobilePhone',
    'LocationName',
    'GPID',
    'FT_EMPLYE_FLG_VAL',
    'USER_ACTIVE',
    'Profile.Name',
    'SmallPhotoUrl',
    'LC_ID__c',
    'WRKFRC_EMPLYMT_TRMNTN_DT__c',
    'Is_Night_Shift__c',
    'UserStatsId',
    'User__c',
    'Start_Time__c',
    'Sunday__c',
    'Monday__c',
    'Tuesday__c',
    'Wednesday__c',
    'Thursday__c',
    'Friday__c',
    'Saturday__c',
    'StartLocation',
    'Sales_Function__c',
    'Manager_Directs__c',
    'OwnerId',
    'SDID',
    'ETRID',
    'ETRUserId',
    'Route__c',
    'LastModifiedDate',
    'RouteId',
    'LOCL_RTE_ID__c',
    'GTMU_RTE_ID__c',
    'SMerchandising_Base__c'
]

const MyTeamListQuery = `
     SELECT
     {User:Id},
     {User:Name},
     {User:FirstName},
     {User:LastName},
     {User:Title},
     {User:GM_LOC_ID__c},
     {User:MobilePhone},
     {User:GM_LOC_NM__c},
     {User:GPID__c},
     {User:FT_EMPLYE_FLG_VAL__c},
     {User:USER_ACTIVE__c},
     {User:Profile.Name},
     {User:SmallPhotoUrl},
     {User:LC_ID__c},
     {User:WRKFRC_EMPLYMT_TRMNTN_DT__c},
     {User_Stats__c:Is_Night_Shift__c},
     {User_Stats__c:Id},
     {User_Stats__c:User__c},
     {User_Stats__c:Start_Time__c},
     {User_Stats__c:Sunday__c},
     {User_Stats__c:Monday__c},
     {User_Stats__c:Tuesday__c},
     {User_Stats__c:Wednesday__c},
     {User_Stats__c:Thursday__c},
     {User_Stats__c:Friday__c},
     {User_Stats__c:Saturday__c},
     {User_Stats__c:Starting_Location__c},
     {User_Stats__c:Sales_Function__c},
     {User_Stats__c:Manager_Directs__c},
     {Service_Detail__c:OwnerId},
     {Service_Detail__c:Id},
     {Employee_To_Route__c:Id},
     {Employee_To_Route__c:User__c},
     {Employee_To_Route__c:Route__c},
     {Employee_To_Route__c:LastModifiedDate},
     {Route_Sales_Geo__c:Id},
     {Route_Sales_Geo__c:LOCL_RTE_ID__c},
     {Route_Sales_Geo__c:GTMU_RTE_ID__c},
     {User_Stats__c:Merchandising_Base__c}
     FROM {User}
     LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
     LEFT JOIN {Service_Detail__c} ON {User:Id} = {Service_Detail__c:OwnerId} AND {Service_Detail__c:Unassigned__c} IS FALSE
     AND {Service_Detail__c:IsRemoved__c} IS FALSE
     LEFT JOIN {Employee_To_Route__c} ON {User:Id} = {Employee_To_Route__c:User__c}
     LEFT JOIN {Route_Sales_Geo__c} ON {Employee_To_Route__c:Route__c} = {Route_Sales_Geo__c:Id}
     WHERE {User:IsActive} IS TRUE
     AND {User:WRKFRC_EMPLYMT_TRMNTN_DT__c} IS NULL
     AND {User:GM_LOC_ID__c} = '%s'
 `

const MyTeamListSDLField = [
    'UserId',
    'Persona',
    'Username',
    'FirstName',
    'LastName',
    'Title',
    'LocationId',
    'MobilePhone',
    'LocationName',
    'GPID',
    'FT_EMPLYE_FLG_VAL',
    'USER_ACTIVE',
    'IsActive',
    'Profile.Name',
    'SmallPhotoUrl',
    'LC_ID__c',
    'WRKFRC_EMPLYMT_TRMNTN_DT__c',
    'UserStatsId',
    'User__c',
    'Start_Time__c',
    'Sunday__c',
    'Monday__c',
    'Tuesday__c',
    'Wednesday__c',
    'Thursday__c',
    'Friday__c',
    'Saturday__c',
    'StartLocation',
    'Sales_Function__c',
    'ETRID',
    'ETRUserId',
    'Route__c',
    'LastModifiedDate',
    'FRouteSalesId',
    'FRouteSales_Parent_Node__c',
    'FRouteSales_SLS_UNIT_ID__c',
    'FRouteSales_RTE_TERR_NM__c',
    'FRouteSales_LOCL_RTE_ID__c',
    'FRouteSales_GTMU_RTE_ID__c',
    'SRouteSalesId',
    'SRouteSales_Parent_Node__c',
    'SRouteSales_SLS_UNIT_ID__c',
    'SRouteSales_RTE_TERR_NM__c',
    'SRouteSales_LOCL_RTE_ID__c',
    'SRouteSales_GTMU_RTE_ID__c',
    'TRouteSalesId',
    'TRouteSales_Parent_Node__c',
    'TRouteSales_SLS_UNIT_ID__c',
    'TRouteSales_RTE_TERR_NM__c',
    'TRouteSales_LOCL_RTE_ID__c',
    'TRouteSales_GTMU_RTE_ID__c'
]

const MyTeamListSDLFieldDelSuP = [
    'UserId',
    'Persona',
    'Username',
    'FirstName',
    'LastName',
    'Title',
    'LocationId',
    'MobilePhone',
    'LocationName',
    'GPID',
    'FT_EMPLYE_FLG_VAL',
    'USER_ACTIVE',
    'Profile.Name',
    'SmallPhotoUrl',
    'LC_ID__c',
    'WRKFRC_EMPLYMT_TRMNTN_DT__c',
    'UserStatsId',
    'User__c',
    'Manager_Directs__c',
    'ETRID',
    'ETRUserId',
    'Route__c',
    'LastModifiedDate',
    'TRouteSalesId',
    'TRouteSales_LOCL_RTE_ID__c',
    'TRouteSales_GTMU_RTE_ID__c'
]

const MyTeamListSDLQueryDelSup = `
    SELECT
        {User:Id},
        {User:PERSONA__c},
        {User:Name},
        {User:FirstName},
        {User:LastName},
        {User:Title},
        {User:GM_LOC_ID__c},
        {User:MobilePhone},
        {User:GM_LOC_NM__c},
        {User:GPID__c},
        {User:FT_EMPLYE_FLG_VAL__c},
        {User:USER_ACTIVE__c},
        {User:Profile.Name},
        {User:SmallPhotoUrl},
        {User:LC_ID__c},
        {User:WRKFRC_EMPLYMT_TRMNTN_DT__c},
        {User_Stats__c:Id},
        {User_Stats__c:User__c},
        {User_Stats__c:Manager_Directs__c},
        {Employee_To_Route__c:Id},
        {Employee_To_Route__c:User__c},
        {Employee_To_Route__c:Route__c},
        {Employee_To_Route__c:LastModifiedDate},
        {Route_Sales_Geo__c:Id},
        {Route_Sales_Geo__c:LOCL_RTE_ID__c},
        {Route_Sales_Geo__c:GTMU_RTE_ID__c}
    FROM {User} 
        LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
        LEFT JOIN {Employee_To_Route__c} ON {User:Id} = {Employee_To_Route__c:User__c}
        LEFT JOIN {Route_Sales_Geo__c} ON {Employee_To_Route__c:Route__c} = {Route_Sales_Geo__c:Id}
    WHERE
        {User:GM_LOC_ID__c} = '%s'
        AND {User:WRKFRC_EMPLYMT_TRMNTN_DT__c} IS NULL
`

const MyTeamListSDLQuery = `
     SELECT
     {User:Id},
     {User:PERSONA__c},
     {User:Name},
     {User:FirstName},
     {User:LastName},
     {User:Title},
     {User:GM_LOC_ID__c},
     {User:MobilePhone},
     {User:GM_LOC_NM__c},
     {User:GPID__c},
     {User:FT_EMPLYE_FLG_VAL__c},
     {User:USER_ACTIVE__c},
     {User:IsActive},
     {User:Profile.Name},
     {User:SmallPhotoUrl},
     {User:LC_ID__c},
     {User:WRKFRC_EMPLYMT_TRMNTN_DT__c},
     {User_Stats__c:Id},
     {User_Stats__c:User__c},
     {User_Stats__c:Start_Time__c},
     {User_Stats__c:Sunday__c},
     {User_Stats__c:Monday__c},
     {User_Stats__c:Tuesday__c},
     {User_Stats__c:Wednesday__c},
     {User_Stats__c:Thursday__c},
     {User_Stats__c:Friday__c},
     {User_Stats__c:Saturday__c},
     {User_Stats__c:Starting_Location__c},
     {User_Stats__c:Sales_Function__c},
     {Employee_To_Route__c:Id},
     {Employee_To_Route__c:User__c},
     {Employee_To_Route__c:Route__c},
     {Employee_To_Route__c:LastModifiedDate},
     FRSG.{Route_Sales_Geo__c:Id},
     FRSG.{Route_Sales_Geo__c:Parent_Node__c},
     FRSG.{Route_Sales_Geo__c:SLS_UNIT_ID__c},
     FRSG.{Route_Sales_Geo__c:RTE_TERR_NM__c},
     FRSG.{Route_Sales_Geo__c:LOCL_RTE_ID__c},
     FRSG.{Route_Sales_Geo__c:GTMU_RTE_ID__c},
     SRSG.{Route_Sales_Geo__c:Id},
     SRSG.{Route_Sales_Geo__c:Parent_Node__c},
     SRSG.{Route_Sales_Geo__c:SLS_UNIT_ID__c},
     SRSG.{Route_Sales_Geo__c:RTE_TERR_NM__c},
     SRSG.{Route_Sales_Geo__c:LOCL_RTE_ID__c},
     SRSG. {Route_Sales_Geo__c:GTMU_RTE_ID__c},
     TRSG.{Route_Sales_Geo__c:Id},
     TRSG.{Route_Sales_Geo__c:Parent_Node__c},
     TRSG.{Route_Sales_Geo__c:SLS_UNIT_ID__c},
     TRSG.{Route_Sales_Geo__c:RTE_TERR_NM__c},
     TRSG.{Route_Sales_Geo__c:LOCL_RTE_ID__c},
     TRSG. {Route_Sales_Geo__c:GTMU_RTE_ID__c}
  FROM {User}
  LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
  LEFT JOIN {Employee_To_Route__c} ON {User:Id} = {Employee_To_Route__c:User__c}
  LEFT JOIN {Route_Sales_Geo__c} FRSG ON FRSG.{Route_Sales_Geo__c:SLS_UNIT_ID__c}= {User:GM_LOC_ID__c}
  LEFT JOIN {Route_Sales_Geo__c} SRSG ON SRSG.{Route_Sales_Geo__c:Parent_Node__c}=FRSG.{Route_Sales_Geo__c:Id}
  LEFT JOIN {Route_Sales_Geo__c} TRSG ON TRSG.{Route_Sales_Geo__c:Parent_Node__c}=SRSG.{Route_Sales_Geo__c:Id}
  AND  TRSG.{Route_Sales_Geo__c:Id}={Employee_To_Route__c:Route__c}
  WHERE {User:GM_LOC_ID__c} = '%s'
  AND {User:WRKFRC_EMPLYMT_TRMNTN_DT__c} IS NULL
 `

const searchModalEEField = [
    'UserId',
    'Username',
    'FirstName',
    'LastName',
    'Title',
    'LocationId',
    'Phone',
    'LocationName',
    'GPID',
    'FT_EMPLYE_FLG_VAL',
    'USER_ACTIVE',
    'Profile.Name',
    'Merchandising_Base_Minimum_Requirement__c',
    'UserStatsId',
    'User__c',
    'Start_Time__c',
    'Sunday__c',
    'Monday__c',
    'Tuesday__c',
    'Wednesday__c',
    'Thursday__c',
    'Friday__c',
    'Saturday__c',
    'StartLocation',
    'SMerchandising_Base__c'
]

const searchModalEEQuery = `
 SELECT
     {User:Id},
     {User:Name},
     {User:FirstName},
     {User:LastName},
     {User:Title},
     {User:GM_LOC_ID__c},
     {User:Phone},
     {User:GM_LOC_NM__c},
     {User:GPID__c},
     {User:FT_EMPLYE_FLG_VAL__c},
     {User:USER_ACTIVE__c},
     {User:Profile.Name},
     {User:Merchandising_Base_Minimum_Requirement__c},
     {User_Stats__c:Id},
     {User_Stats__c:User__c},
     {User_Stats__c:Start_Time__c},
     {User_Stats__c:Sunday__c},
     {User_Stats__c:Monday__c},
     {User_Stats__c:Tuesday__c},
     {User_Stats__c:Wednesday__c},
     {User_Stats__c:Thursday__c},
     {User_Stats__c:Friday__c},
     {User_Stats__c:Saturday__c},
     {User_Stats__c:Starting_Location__c},
     {User_Stats__c:Merchandising_Base__c}
     FROM {User}
     LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
`

const searchModalLocationField = [
    'RouteId',
    'RouteName',
    'ADDR_LN_1_TXT__c',
    'ADDR_LN_2_TXT__c',
    'CITY_NM__c',
    'PSTL_AREA_VAL__c',
    'SLS_UNIT_NM__c',
    'SLS_UNIT_ID__c'
]

const searchModalLocationQuery = `
    SELECT
        {Route_Sales_Geo__c:Id},
        {Route_Sales_Geo__c:Name},
        {Route_Sales_Geo__c:ADDR_LN_1_TXT__c},
        {Route_Sales_Geo__c:ADDR_LN_2_TXT__c},
        {Route_Sales_Geo__c:CITY_NM__c},
        {Route_Sales_Geo__c:PSTL_AREA_VAL__c},
        {Route_Sales_Geo__c:SLS_UNIT_NM__c},
        {Route_Sales_Geo__c:SLS_UNIT_ID__c}
        FROM {Route_Sales_Geo__c}
    `

const EmployeeDetailReassignUserListField = [
    'UserId',
    'Username',
    'FirstName',
    'LastName',
    'Title',
    'LocationId',
    'MobilePhone',
    'LocationName',
    'GPID',
    'FT_EMPLYE_FLG_VAL',
    'USER_ACTIVE',
    'Profile.Name',
    'SmallPhotoUrl',
    'UserStatsId',
    'Sunday__c',
    'Monday__c',
    'Tuesday__c',
    'Wednesday__c',
    'Thursday__c',
    'Friday__c',
    'Saturday__c',
    'Start_Time__c',
    'RouteId',
    'User__c',
    'CTRId',
    'CTROwnerId',
    'CTRCustomerId'
]

const EmployeeDetailReassignUserListQuery = `
     SELECT
     {User:Id},
     {User:Name},
     {User:FirstName},
     {User:LastName},
     {User:Title},
     {User:GM_LOC_ID__c},
     {User:MobilePhone},
     {User:GM_LOC_NM__c},
     {User:GPID__c},
     {User:FT_EMPLYE_FLG_VAL__c},
     {User:USER_ACTIVE__c},
     {User:Profile.Name},
     {User:SmallPhotoUrl},
     {User_Stats__c:Id},
     {User_Stats__c:Sunday__c},
     {User_Stats__c:Monday__c},
     {User_Stats__c:Tuesday__c},
     {User_Stats__c:Wednesday__c},
     {User_Stats__c:Thursday__c},
     {User_Stats__c:Friday__c},
     {User_Stats__c:Saturday__c},
     {User_Stats__c:Start_Time__c},
     {Route_Sales_Geo__c:Id},
     {Route_Sales_Geo__c:OwnerId},
     {Customer_to_Route__c:Id},
     {Customer_to_Route__c:OwnerId},
     {Customer_to_Route__c:Customer__c}
     FROM {User}
     LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
     LEFT JOIN {Route_Sales_Geo__c} ON {Route_Sales_Geo__c:OwnerId} = {User:Id} 
     AND {Route_Sales_Geo__c:Merch_Flag__c} IS TRUE
     LEFT JOIN {Customer_to_Route__c} ON {Customer_to_Route__c:Route__c} = {Route_Sales_Geo__c:Id} 
     AND {Customer_to_Route__c:IsRemoved__c} IS FALSE
     AND {Customer_to_Route__c:RecordTypeId} = '%s'
     WHERE
     {User_Stats__c:Merchandising_Base__c} IS TRUE AND
     {User:GM_LOC_ID__c} = '%s'
     ORDER BY {User:LastName}
 `

const EmployeeScheduleMeetingQuery = `
                    SELECT
                      {Event:Id} AS Id,
                      null AS Pull_Number__c,
                      null AS Take_Order_Flag__c,
                      null AS Visit_Subtype__c,
                      null AS Planned_Date__c,
                      null AS Planned_Duration_Minutes__c,
                      null AS InstructionDescription,
                      null AS VisitList,
                      null AS StartTime,
                      null AS VisitDate,
                      null AS VlStatus,
                      '0' AS TotalPlannedTime,
                      '0' AS PlannedMileage,
                      null AS EndTime,
                      {Event:Actual_Start_Time__c} AS ActualStartTime,
                      {Event:Actual_End_Time__c} AS ActualEndTime,
                      null AS Actual_Duration_Minutes__c,
                      null AS Check_Out_Location_Flag__c,
                      null AS StoreId,
                      null AS AccountId,
                      {Event:Subject} AS Name,
                      {Event:Actual_End_Time__c} IS NULL AS Finished,
                      null AS Sequence,
                      null AS Status,
                      null AS Street,
                      null AS Address,
                      null AS Latitude,
                      null AS Longitude,
                      null AS StoreLocation,
                      null AS AccountPhone,
                      null AS OrderDays,
                      null AS AdHoc,
                      null AS ManagerAdHoc,
                      null AS Planned_Duration_Minutes__c,
                      null AS Planned_Travel_Time__c,
                      null AS Planned_Mileage__c,
                      null AS WorkOrder,
                      {Event:SubType__c} AS SubType,
                      {Event:OwnerId} AS OwnerId,
                      {Event:StartDateTime} AS PlannedStartTime,
                      {Event:EndDateTime} AS PlannedEndTime,
                      '0' AS InLocation,
                      null AS RecordTypeName
`
const getPublishVisitListField = [
    'Id',
    'StartTime',
    'VisitDate',
    'TotalPlannedTime',
    'PlannedMileage',
    'EndTime',
    'ActualVisitStartTime',
    'ActualVisitEndTime',
    'Actual_Duration_Minutes__c',
    'Check_Out_Location_Flag__c',
    'storeId',
    'name',
    'Finished',
    'sequence',
    'status',
    'latitude',
    'longitude',
    'storeLocation',
    'AccountPhone',
    'AdHoc',
    'Manager_Ad_Hoc__c',
    'PlannedDurationMinutes',
    'PlannedTravelTime',
    'Planned_Mileage__c',
    'InstructionDescription',
    'workOrders',
    'SubType',
    'OwnerId',
    'PlanStartTime',
    'PlanEndTime',
    'InLocation',
    'Pull_Number__c',
    'Take_Order_Flag__c',
    'Visit_Subtype__c',
    'Planned_Date__c',
    'VisitorId',
    'Visit_List__c',
    'Route_Group__c',
    'ShippingAddress',
    'cof',
    'busnLvl3',
    'customNumber',
    'Sales_Rep_Info__c',
    'LOCL_RTE_ID__c',
    'GTMU_RTE_ID__c',
    'UserId',
    'userName',
    'FirstName',
    'LastName',
    'UserStatsId'
]
const getPublishVisitListBaseQuery = `
SELECT
    {Visit:Id} AS Id,
    {Visit_List__c:Start_Time__c} AS StartTime,
    {Visit_List__c:Visit_Date__c} AS VisitDate,
    {Visit_List__c:Total_Planned_Time__c} AS TotalPlannedTime,
    {Visit_List__c:Planned_Mileage__c} AS PlannedMileage,
    {Visit_List__c:End_Time__c} AS EndTime,
    {Visit:ActualVisitStartTime} AS ActualStartTime,
    {Visit:ActualVisitEndTime} AS ActualEndTime,
    {Visit:Actual_Duration_Minutes__c} AS Actual_Duration_Minutes__c,
    {Visit:Check_Out_Location_Flag__c},
    {RetailStore:Id} AS StoreId,
    {RetailStore:Account.Name} AS Name,
    {Visit:ActualVisitEndTime} IS NULL AS Finished,
    {Visit:Sequence__c} AS Sequence,
    {Visit:Status__c} AS Status,
    {RetailStore:Latitude} AS Latitude,
    {RetailStore:Longitude} AS Longitude,
    {RetailStore:Store_Location__c} AS StoreLocation,
    {RetailStore:Account.Phone} AS AccountPhone,
    {Visit:Ad_Hoc__c} AS AdHoc,
    {Visit:Manager_Ad_Hoc__c},
    {Visit:Planned_Duration_Minutes__c},
    {Visit:Planned_Travel_Time__c},
    {Visit:Planned_Mileage__c},
    {Visit:InstructionDescription},
    (${WorkOrderService.workOrderQuery()}) WorkOrder,
    'Visit' AS SubType,
    {Visit:OwnerId} AS OwnerId,
    {Visit:PlannedVisitStartTime} AS PlannedStartTime,
    {Visit:PlannedVisitEndTime} AS PlannedEndTime,
    {Visit:AMAS_Compliant__c} AS InLocation,
    {Visit:Pull_Number__c} AS pullNumber,
    {Visit:Take_Order_Flag__c},
    {Visit:Visit_Subtype__c},
    {Visit:Planned_Date__c},
    {Visit:VisitorId} AS VisitorId,
    {Visit:Visit_List__c} AS Visit_List__c,
    {Visit:Route_Group__c},
    {RetailStore:Account.ShippingAddress},
    {RetailStore:Account.CUST_ID__c},
    {RetailStore:Account.BUSN_SGMNTTN_LVL_3_NM__c},
    {RetailStore:Account.RTLR_STOR_NUM__c},
    {RetailStore:Account.Sales_Rep_Info__c},
    RSG.{Route_Sales_Geo__c:LOCL_RTE_ID__c},
    RSG.{Route_Sales_Geo__c:GTMU_RTE_ID__c},
    {User:Id},
    {User:Name},
    {User:FirstName},
    {User:LastName},
    {User_Stats__c:Id}
    FROM {Visit}
    JOIN {RetailStore} ON {Visit:PlaceId} = {RetailStore:Id}
    LEFT JOIN {Visit_List__c} ON {Visit:Visit_List__c} = {Visit_List__c:Id}
    LEFT JOIN {User} ON {Visit:VisitorId} = {User:Id}
    LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
    LEFT JOIN {Route_Sales_Geo__c} RSG ON {RetailStore:Account.Sales_Route__c} = RSG.{Route_Sales_Geo__c:Id}
`

const PublishUnassignedVisitsField = [
    'Id',
    'VisitorId',
    'Status__c',
    'Planned_Date__c',
    'Planned_Duration_Minutes__c',
    'Sequence__c',
    'Pull_Number__c',
    'Planned_Travel_Time__c',
    'Scheduled_Case_Quantity__c',
    'Planned_Mileage__c',
    'Visit_Subtype__c',
    'Take_Order_Flag__c',
    'InstructionDescription',
    'Manager_Ad_Hoc__c',
    'Route_Group__c',
    'UserId',
    'Username',
    'FirstName',
    'LastName',
    'LocationId',
    'Title',
    'MobilePhone',
    'FT_EMPLYE_FLG_VAL__c',
    'StoreId',
    'StoreName',
    'Street',
    'City',
    'State',
    'Country',
    'PostalCode',
    'OwnerId',
    'StoreNumber',
    'COF',
    'busnLvl3',
    'AccountPhone',
    'AccountName',
    'ShippingAddress',
    'Sales_Rep_Info',
    'Latitude',
    'Longitude',
    'Store_Location__c',
    'LOCL_RTE_ID__c',
    'GTMU_RTE_ID__c',
    'UserStatsId',
    'User__c',
    'Start_Time__c',
    'Sunday__c',
    'Monday__c',
    'Tuesday__c',
    'Wednesday__c',
    'Thursday__c',
    'Friday__c',
    'Saturday__c'
]
const PublishUnassignedVisitsQuery = `
 SELECT
     {Visit:Id},
     {Visit:VisitorId},
     {Visit:Status__c},
     {Visit:Planned_Date__c},
     {Visit:Planned_Duration_Minutes__c},
     {Visit:Sequence__c},
     {Visit:Pull_Number__c},
     {Visit:Planned_Travel_Time__c},
     {Visit:Scheduled_Case_Quantity__c},
     {Visit:Planned_Mileage__c},
     {Visit:Visit_Subtype__c},
     {Visit:Take_Order_Flag__c},
     {Visit:InstructionDescription},
     {Visit:Manager_Ad_Hoc__c},
     {Visit:Route_Group__c},
     {User:Id},
     {User:Name},
     {User:FirstName},
     {User:LastName},
     {User:GM_LOC_ID__c},
     {User:Title},
     {User:MobilePhone},
     {User:FT_EMPLYE_FLG_VAL__c},
     {RetailStore:Id},
     {RetailStore:Name},
     {RetailStore:Street},
     {RetailStore:City},
     {RetailStore:State},
     {RetailStore:Country},
     {RetailStore:PostalCode},
     {RetailStore:OwnerId},
     {RetailStore:RTLR_STOR_NUM__c},
     {RetailStore:Account.CUST_UNIQ_ID_VAL__c},
     {RetailStore:Account.BUSN_SGMNTTN_LVL_3_NM__c},
     {RetailStore:Account.Phone},
     {RetailStore:Account.Name},
     {RetailStore:Account.ShippingAddress},
     {RetailStore:Account.Sales_Rep_Info__c},
     {RetailStore:Latitude},
     {RetailStore:Longitude},
     {RetailStore:Store_Location__c},
     RSG.{Route_Sales_Geo__c:LOCL_RTE_ID__c},
     RSG.{Route_Sales_Geo__c:GTMU_RTE_ID__c},
     {User_Stats__c:Id},
     {User_Stats__c:User__c},
     {User_Stats__c:Start_Time__c},
     {User_Stats__c:Sunday__c},
     {User_Stats__c:Monday__c},
     {User_Stats__c:Tuesday__c},
     {User_Stats__c:Wednesday__c},
     {User_Stats__c:Thursday__c},
     {User_Stats__c:Friday__c},
     {User_Stats__c:Saturday__c}
     FROM {RetailStore} 
     LEFT JOIN {Visit} ON {RetailStore:Id} = {Visit:PlaceId}  
     LEFT JOIN {Route_Sales_Geo__c} RSG ON {RetailStore:Account.Sales_Route__c} = RSG.{Route_Sales_Geo__c:Id} 
     LEFT JOIN {User} ON {Visit:VisitorId} = {User:Id}
     LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
     WHERE {Visit:Schedule_Visit_Group__c} = '%s'
     AND ({Visit:Status__c} = 'Published' AND {Visit:Visit_List__c} IS NULL AND {Visit:VisitorId} IS NULL)
     GROUP BY {Visit:Id}
     ORDER BY {RetailStore:Id}, {Visit:Planned_Date__c}, {Visit:Pull_Number__c} NULLS LAST
 `

const MyCustomersQuery = `
    SELECT 
    {RetailStore:Id},
    {RetailStore:Account.IsOTSCustomer__c},
    {RetailStore:Account.CDA_Medal__c},
    {RetailStore:Name},
    {RetailStore:Latitude},
    {RetailStore:Longitude},
    {RetailStore:Store_Location__c},
    {RetailStore:AccountId},
    {RetailStore:Account.Name},
    {RetailStore:Account.CUST_UNIQ_ID_VAL__c},
    {RetailStore:Account.RTLR_STOR_NUM__c},
    {RetailStore:LOC_PROD_ID__c},
    {RetailStore:Account.Merchandising_Base_Minimum_Requirement__c},
    {RetailStore:Account.Phone},
    {RetailStore:Account.BUSN_SGMNTTN_LVL_3_NM__c},
    {RetailStore:Account.Merchandising_Base__c},
    {RetailStore:Account.ShippingAddress},
    {RetailStore:Account.CUST_ID__c},
    {RetailStore:Account.Merchandising_Order_Days__c},
    {RetailStore:Account.Merchandising_Delivery_Days__c},
    {RetailStore:Account.Sales_Route__c},
    {RetailStore:Account.Sales_Rep__c},
    {RetailStore:Account.IS_ACTIVE__c},
    {RetailStore:Account.Active_Dist_Points__c},
    {RetailStore:Account.Sales_Rep_Info__c},
    {RetailStore:Account.Indicator_2P__c},
    RSG.{Route_Sales_Geo__c:Id},
    RSG.{Route_Sales_Geo__c:LOCL_RTE_ID__c},
    RSG.{Route_Sales_Geo__c:GTMU_RTE_ID__c},
    US.{User_Stats__c:Id},
    US.{User_Stats__c:Start_Time__c},
    US.{User_Stats__c:Sunday__c},
    US.{User_Stats__c:Monday__c},
    US.{User_Stats__c:Tuesday__c},
    US.{User_Stats__c:Wednesday__c},
    US.{User_Stats__c:Thursday__c},
    US.{User_Stats__c:Friday__c},
    US.{User_Stats__c:Saturday__c},
    US.{User_Stats__c:Merchandising_Base__c}
    %s
    FROM {RetailStore} 
    LEFT JOIN {Route_Sales_Geo__c} RSG ON {RetailStore:Account.Sales_Route__c} = RSG.{Route_Sales_Geo__c:Id} 
    LEFT JOIN {User_Stats__c} US ON {RetailStore:Account.Sales_Rep__c} = US.{User_Stats__c:User__c} 
`

const UnassignedEEQuery = `
    SELECT
    {User:Id},
    {User:Name},
    {User:FirstName},
    {User:LastName},
    {User:Title},
    {User:FT_EMPLYE_FLG_VAL__c},
    {User_Stats__c:Id},
    {User_Stats__c:Sunday__c},
    {User_Stats__c:Monday__c},
    {User_Stats__c:Tuesday__c},
    {User_Stats__c:Wednesday__c},
    {User_Stats__c:Thursday__c},
    {User_Stats__c:Friday__c},
    {User_Stats__c:Saturday__c},
    WVL.{Visit_List__c:Unassigned_Employee_Time__c},
    WVL.{Visit_List__c:Unassigned_Employee_Cost__c},
    WVL.{Visit_List__c:Unscheduled_Cost_Inclusion__c},
    WVL.{Visit_List__c:Id}
    FROM {User}
    LEFT JOIN {User_Stats__c} ON {User_Stats__c:User__c} = {User:Id}
    LEFT JOIN {Visit_List__c} WVL ON WVL.{Visit_List__c:OwnerId} = {User:Id} 
    AND WVL.{Visit_List__c:IsRemoved__c} IS FALSE
    AND WVL.{Visit_List__c:Unscheduled__c} IS TRUE 
    WHERE WVL.{Visit_List__c:Id} IS NOT NULL 
    AND WVL.{Visit_List__c:Visit_List_Group__c} IS NULL
    AND WVL.{Visit_List__c:Start_Date__c} = '%s'
    AND WVL.{Visit_List__c:End_Date__c} = '%s'
`

const UnassignedEEField = [
    'Id',
    'Name',
    'FirstName',
    'LastName',
    'Title',
    'FT_EMPLYE_FLG_VAL',
    'UserStatsId',
    'Sunday__c',
    'Monday__c',
    'Tuesday__c',
    'Wednesday__c',
    'Thursday__c',
    'Friday__c',
    'Saturday__c',
    'Unassigned_Employee_Time__c',
    'Unassigned_Employee_Cost__c',
    'Unscheduled_Cost_Inclusion__c',
    'WVLId'
]

const updateVisitForDeleteFields = [
    'Id',
    'OwnerId',
    'PlaceId',
    'VisitorId',
    'Status__c',
    'PlannedVisitEndTime',
    'PlannedVisitStartTime',
    'Ad_Hoc__c',
    'RecordTypeId',
    'Planned_Date__c',
    'Sequence__c',
    'Pull_Number__c',
    'Planned_Travel_Time__c',
    'Scheduled_Case_Quantity__c',
    'Planned_Mileage__c',
    'Planned_Duration_Minutes__c',
    'Schedule_Visit_Group__c',
    'Visit_List__c',
    'Visit_Subtype__c',
    'Take_Order_Flag__c',
    'InstructionDescription',
    'Manager_Ad_Hoc__c',
    'Sales_Visit__c',
    'Route_Group__c',
    'Dynamic_Frequency_Add__c',
    'Dynamic_Frequency_Remove__c',
    'Reassigned__c'
]

const updateVisitForDeleteQuery = `
        SELECT
            {Visit:Id},
            {Visit:OwnerId},
            {Visit:PlaceId},
            {Visit:VisitorId},
            {Visit:Status__c},
            {Visit:PlannedVisitEndTime},
            {Visit:PlannedVisitStartTime},
            {Visit:Ad_Hoc__c},
            {Visit:RecordTypeId},
            {Visit:Planned_Date__c},
            {Visit:Sequence__c},
            {Visit:Pull_Number__c},
            {Visit:Planned_Travel_Time__c},
            {Visit:Scheduled_Case_Quantity__c},
            {Visit:Planned_Mileage__c},
            {Visit:Planned_Duration_Minutes__c},
            {Visit:Schedule_Visit_Group__c},
            {Visit:Visit_List__c},
            {Visit:Visit_Subtype__c},
            {Visit:Take_Order_Flag__c},
            {Visit:InstructionDescription},
            {Visit:Manager_Ad_Hoc__c},
            {Visit:Sales_Visit__c},
            {Visit:Route_Group__c},
            {Visit:Dynamic_Frequency_Add__c},
            {Visit:Dynamic_Frequency_Remove__c},
            {Visit:Reassigned__c},
            {Visit:_soupEntryId},
            {Visit:__local__},
            {Visit:__locally_created__},
            {Visit:__locally_updated__},
            {Visit:__locally_deleted__}
        FROM {Visit}
        `

const ScheduleQuery = {
    getEmployeeQuery: {
        q: `${EmployeeQuerySelect}
         ${EmployeeQueryOrderBy}
     `,
        f: [
            'Id',
            'Name',
            'FirstName',
            'LastName',
            'Phone',
            'LC_ID__c',
            'GM_LOC_ID__c',
            'GPID__c',
            'BU_ID__c',
            'PERSONA__c',
            'Title',
            'MobilePhone',
            'FT_EMPLYE_FLG_VAL__c',
            'UserStatsId',
            'Schedule_Favorited__c',
            'Manager_Directs__c',
            'Start_Date_Time__c',
            'End_Date_Time__c',
            'OwnerId',
            'Visit_List_Status',
            'Visit_Date__c',
            'Visits_Id',
            'IsRemoved__c',
            'Total_Planned_Time__c',
            'Unscheduled__c',
            'Planned_Date__c',
            'VisitId',
            'RecordTypeId',
            'RecordType_DeveloperName',
            'Visit_List__c',
            'VisitorId',
            'PlannedVisitStartTime',
            'ActualVisitEndTime',
            'ActualVisitStartTime',
            'Status__c',
            'Sequence__c',
            'Planned_Duration_Minutes__c',
            'Visit_Subtype__c',
            'Take_Order_Flag__c',
            'AMAS_Compliant__c',
            'Pull_Number__c',
            'InstructionDescription',
            'Planned_Mileage__c',
            'Planned_Travel_Time__c',
            'storeId',
            'Street',
            'City',
            'State',
            'Country',
            'PostalCode',
            'Latitude',
            'Longitude',
            'Store_Location__c',
            'StoreName',
            'AccountPhone',
            'EventId',
            'StartDateTime'
        ]
    },
    getPublishVisitList: {
        baseQuery: getPublishVisitListBaseQuery,
        f: getPublishVisitListField,
        copilotCondition: `WHERE ({Visit:Status__c} = 'Complete' OR {Visit:Status__c} = 'In Progress' OR {Visit:Status__c} = 'Published')
        AND {Visit_List__c:Visit_Date__c} = date("%s")
        AND {Visit_List__c:IsRemoved__c} IS NOT TRUE
        AND {User:GM_LOC_ID__c} = '%s'
        ORDER BY Name, pullNumber NULLS LAST`,
        myDayCondition: `WHERE ({Visit:Status__c} = 'Complete' OR {Visit:Status__c} = 'In Progress' OR {Visit:Status__c} = 'Published')
        AND ({Visit_List__c:Visit_Date__c} = date("%s")
        AND {Visit_List__c:IsRemoved__c} IS NOT TRUE
        AND {Visit_List__c:RecordType.DeveloperName} = 'Daily_Visit_List'
        AND {User:GM_LOC_ID__c} = '%s'
        OR ({Visit:Status__c} = 'Published' AND {Visit:VisitorId} IS NULL))
        AND {Visit:RecordType.DeveloperName} = 'Merchandising'
        ORDER BY Name, pullNumber NULLS LAST`
    },
    getPublishUnassignedVisits: {
        q: PublishUnassignedVisitsQuery,
        f: PublishUnassignedVisitsField
    },
    retrieveVisitListData: {
        q: AllVisitListQuery,
        f: AllVisitListField
    },
    retrieveVisitData: {
        q: AllVisitQuery,
        f: AllVisitField
    },
    retrieveVisitAndStoreData: {
        q: VisitAndStoreQuery,
        f: VisitAndStoreField
    },
    retrieveUserData: {
        q: AllUserQuery,
        f: AllUserField
    },
    // when adding new fields here, please add to meeting service too, see the reference
    retrieveRNSEmployeeData: {
        q: RNSEmployeeQuery,
        f: RNSEmployeeField
    },
    retrieveRNSCustomerData: {
        q: RNSCustomerQuery,
        f: RNSCustomerField
    },
    retrieveRNSOptimizedCustomerData: {
        q: RNSOptimizedCustomerQuery,
        f: RNSCustomerField
    },
    retrieveRNSAssignList: {
        q: RNSEmployeeAssignListQuery,
        f: RNSEmployeeAssignListField
    },
    retrieveMyTeamList: {
        q: MyTeamListQuery,
        f: MyTeamListField,
        c: ' AND {User_Stats__c:Merchandising_Base__c} IS TRUE',
        orderBy: ' ORDER BY {User:Id}, {Employee_To_Route__c:LastModifiedDate}'
    },
    retrieveMyTeamSDLList: {
        q: MyTeamListSDLQuery,
        f: MyTeamListSDLField,
        qDelSup: MyTeamListSDLQueryDelSup,
        fDelSup: MyTeamListSDLFieldDelSuP,
        orderBy: ' ORDER BY {User:Id}, {Employee_To_Route__c:LastModifiedDate}'
    },
    retrieveEmployeeDetailReassignUserList: {
        q: EmployeeDetailReassignUserListQuery,
        f: EmployeeDetailReassignUserListField
    },
    retrieveSearchModalEE: {
        q: searchModalEEQuery,
        f: searchModalEEField
    },
    retrieveSearchModalLocation: {
        q: searchModalLocationQuery,
        f: searchModalLocationField
    },
    getEmployeeScheduleQuery: {
        queryScheduleMeeting: EmployeeScheduleMeetingQuery,
        salesF: [
            'Id',
            'VisitorId',
            'PlaceId',
            'Pull_Number__c',
            'Take_Order_Flag__c',
            'Visit_Subtype__c',
            'Planned_Date__c',
            'Planned_Duration_Minutes__c',
            'InstructionDescription',
            'visitList',
            'StartTime',
            'VisitDate',
            'VlStatus',
            'TotalPlannedTime',
            'PlannedMileage',
            'EndTime',
            'punchIn',
            'punchOut',
            'ActualVisitStartTime',
            'ActualVisitEndTime',
            'Actual_Duration_Minutes__c',
            'Check_Out_Location_Flag__c',
            'storeId',
            'AccountId',
            'name',
            'Finished',
            'sequence',
            'status',
            'address',
            'cityStateZip',
            'latitude',
            'longitude',
            'storeLocation',
            'AccountPhone',
            'OrderDays',
            'AdHoc',
            'ManagerAdHoc',
            'PlannedDurationMinutes',
            'PlannedTravelTime',
            'Planned_Mileage__c',
            'workOrders',
            'SubType',
            'OwnerId',
            'PlanStartTime',
            'PlanEndTime',
            'Manager_Scheduled',
            'InLocation',
            'inLocation',
            'RecordTypeName',
            'uid'
        ],
        merchF: [
            'Id',
            'VisitorId',
            'PlaceId',
            'Pull_Number__c',
            'Take_Order_Flag__c',
            'Visit_Subtype__c',
            'Planned_Date__c',
            'Planned_Duration_Minutes__c',
            'InstructionDescription',
            'visitList',
            'StartTime',
            'VisitDate',
            'VlStatus',
            'TotalPlannedTime',
            'PlannedMileage',
            'EndTime',
            'StartGap',
            'EndGap',
            'KronosPunchIn',
            'KronosPunchOut',
            'ActualVisitStartTime',
            'ActualVisitEndTime',
            'Actual_Duration_Minutes__c',
            'Check_Out_Location_Flag__c',
            'storeId',
            'AccountId',
            'name',
            'Finished',
            'sequence',
            'status',
            'address',
            'cityStateZip',
            'latitude',
            'longitude',
            'storeLocation',
            'AccountPhone',
            'OrderDays',
            'AdHoc',
            'ManagerAdHoc',
            'PlannedDurationMinutes',
            'PlannedTravelTime',
            'Planned_Mileage__c',
            'workOrders',
            'CompletedWorkOrders',
            'SubType',
            'OwnerId',
            'PlanStartTime',
            'PlanEndTime',
            'Manager_Scheduled',
            'InLocation',
            'RecordTypeName',
            ''
        ],
        f: [
            'Id',
            'VisitorId',
            'PlaceId',
            'Pull_Number__c',
            'Take_Order_Flag__c',
            'Visit_Subtype__c',
            'Planned_Date__c',
            'Planned_Duration_Minutes__c',
            'InstructionDescription',
            'visitList',
            'StartTime',
            'VisitDate',
            'VlStatus',
            'TotalPlannedTime',
            'PlannedMileage',
            'EndTime',
            'StartGap',
            'EndGap',
            'ActualVisitStartTime',
            'ActualVisitEndTime',
            'Actual_Duration_Minutes__c',
            'Check_Out_Location_Flag__c',
            'storeId',
            'AccountId',
            'name',
            'Finished',
            'sequence',
            'status',
            'address',
            'cityStateZip',
            'latitude',
            'longitude',
            'storeLocation',
            'AccountPhone',
            'OrderDays',
            'AdHoc',
            'ManagerAdHoc',
            'PlannedDurationMinutes',
            'PlannedTravelTime',
            'Planned_Mileage__c',
            'workOrders',
            'SubType',
            'OwnerId',
            'PlanStartTime',
            'PlanEndTime',
            'Manager_Scheduled',
            'InLocation',
            'RecordTypeName',
            ''
        ],
        deliveryF: [
            'Id',
            'VisitorId',
            'PlaceId',
            'Pull_Number__c',
            'Take_Order_Flag__c',
            'Visit_Subtype__c',
            'Planned_Date__c',
            'Planned_Duration_Minutes__c',
            'InstructionDescription',
            'visitList',
            'StartTime',
            'VisitDate',
            'VlStatus',
            'TotalPlannedTime',
            'PlannedMileage',
            'EndTime',
            'StartGap',
            'EndGap',
            'GateCheckOut',
            'GateCheckIn',
            'ManifestOut',
            'ManifestIn',
            'ActualVisitStartTime',
            'ActualVisitEndTime',
            'Actual_Duration_Minutes__c',
            'Check_Out_Location_Flag__c',
            'storeId',
            'AccountId',
            'name',
            'Finished',
            'sequence',
            'status',
            'address',
            'cityStateZip',
            'latitude',
            'longitude',
            'storeLocation',
            'AccountPhone',
            'OrderDays',
            'AdHoc',
            'ManagerAdHoc',
            'PlannedDurationMinutes',
            'PlannedTravelTime',
            'Planned_Mileage__c',
            'workOrders',
            'SubType',
            'OwnerId',
            'PlanStartTime',
            'PlanEndTime',
            'Manager_Scheduled',
            'InLocation',
            'RecordTypeName',
            ''
        ]
    },
    getLineCodeQuery: {
        f: ['lineCode', 'teamGroup', 'landingGrouping'],
        q: `SELECT
     {Line_Code_Grouping_Definition__mdt:Line_Code_ID__c},
     {Line_Code_Grouping_Definition__mdt:My_Team_Grouping__c},
     {Line_Code_Grouping_Definition__mdt:Landing_Page_Grouping__c}
     FROM {Line_Code_Grouping_Definition__mdt}`
    },
    getMyCustomerQuery: {
        q: MyCustomersQuery,
        f: [
            'Id',
            'Account.IsOTSCustomer__c',
            'Account.CDA_Medal__c',
            'Name',
            'Latitude',
            'Longitude',
            'Store_Location__c',
            'AccountId',
            'Account.Name',
            'Account.CUST_UNIQ_ID_VAL__c',
            'Account.RTLR_STOR_NUM__c',
            'LOC_PROD_ID__c',
            'Account.Merchandising_Base_Minimum_Requirement__c',
            'Account.Phone',
            'Account.BUSN_SGMNTTN_LVL_3_NM__c',
            'Account.Merchandising_Base__c',
            'Account.ShippingAddress',
            'Account.CUST_ID__c',
            'Account.Merchandising_Order_Days__c',
            'Account.Merchandising_Delivery_Days__c',
            'Account.Sales_Route__c',
            'Account.Sales_Rep__c',
            'Account.IS_ACTIVE__c',
            'Account.Active_Dist_Points__c',
            'Account.Sales_Rep_Info__c',
            'Account.Indicator_2P__c',
            'RSG.Id',
            'RSG.LOCL_RTE_ID__c',
            'RSG.GTMU_RTE_ID__c',
            'US.Id',
            'US.Start_Time__c',
            'US.Sunday__c',
            'US.Monday__c',
            'US.Tuesday__c',
            'US.Wednesday__c',
            'US.Thursday__c',
            'US.Friday__c',
            'US.Saturday__c',
            'US.Merchandising_Base__c',
            'recVisitCount',
            'unassignedVisitCount'
        ]
    },
    getManagerMeetingDetail: {
        q: ` 
            SELECT 
            OEV.{Event:Id},
            OEV.{Event:ActivityDate},
            OEV.{Event:StartDateTime},
            OEV.{Event:EndDateTime},
            OEV.{Event:MeetingName__c},
            OEV.{Event:VirtualLocation__c},
            OEV.{Event:Planned_Duration__c},
            OEV.{Event:Aggregate_Duration__c},
            OEV.{Event:Planned_Cost__c},
            OEV.{Event:Location},
            OEV.{Event:Location__c},
            OEV.{Event:Description},
            OEV.{Event:_soupEntryId},
            OEV.{Event:Visit_List__c},
            OEV.{Event:WhatId},
            OEV.{Event:Actual_Start_Time__c},
            OEV.{Event:Actual_End_Time__c},
            NEV.{Event:Id},
            NEV.{Event:OwnerId},
            NEV.{Event:_soupEntryId},
            NEV.{Event:Visit_List__c},
            NEV.{Event:Actual_Start_Time__c},
            NEV.{Event:Actual_End_Time__c},
            NEV.{Event:WhatId}
            FROM {Event} OEV
            LEFT JOIN {Event} NEV ON NEV.{Event:Parent_Event__c} = OEV.{Event:Id}
            %s
            WHERE OEV.{Event:Manager_Scheduled__c} IS TRUE
            AND OEV.{Event:Parent_Event__c} IS NULL
            AND NEV.{Event:IsRemoved__c} IS FALSE
            AND OEV.{Event:IsRemoved__c} IS FALSE
        `,
        merchdiserQ: ` 
            SELECT 
            {Event:Id},
            {Event:ActivityDate},
            {Event:StartDateTime},
            {Event:EndDateTime},
            {Event:MeetingName__c},
            {Event:VirtualLocation__c},
            {Event:Planned_Duration__c},
            {Event:Aggregate_Duration__c},
            {Event:Planned_Cost__c},
            {Event:Location},
            {Event:Location__c},
            {Event:Description},
            {Event:_soupEntryId},
            {Event:Visit_List__c},
            {Event:WhatId},
            {Event:Actual_Start_Time__c},
            {Event:Actual_End_Time__c},
            null AS ChildId,
            {Event:OwnerId},
            null AS ChildSoupEntryId,
            null AS ChildVisitListId,
            null AS ChildWhatId
            FROM {Event} WHERE {Event:Manager_Scheduled__c} IS TRUE
        `,
        f: [
            'Id',
            'ActivityDate',
            'StartDateTime',
            'EndDateTime',
            'MeetingName',
            'VirtualLocation',
            'PlannedDuration',
            'AggregateDuration',
            'PlannedCost',
            'Location',
            'LocationId',
            'Description',
            'SoupEntryId',
            'VisitListId',
            'WhatId',
            'Actual_Start_Time__c',
            'Actual_End_Time__c',
            'ChildId',
            'OwnerId',
            'ChildSoupEntryId',
            'ChildVisitListId',
            'ChildActualStartTime',
            'ChildActualEndTime',
            'ChildWhatId'
        ],
        merchdiserF: [
            'Id',
            'ActivityDate',
            'StartDateTime',
            'EndDateTime',
            'MeetingName',
            'VirtualLocation',
            'PlannedDuration',
            'AggregateDuration',
            'PlannedCost',
            'Location',
            'LocationId',
            'Description',
            'SoupEntryId',
            'VisitListId',
            'WhatId',
            'Actual_Start_Time__c',
            'Actual_End_Time__c'
        ]
    },
    retrieveDefaultLocationInfo: {
        q: `
            SELECT 
            {Route_Sales_Geo__c:Default_Start_Time__c},
            {Route_Sales_Geo__c:Default_Starting_Location__c} ,
            {Route_Sales_Geo__c:Id} ,
            {Route_Sales_Geo__c:SLS_UNIT_NM__c} ,
            {Route_Sales_Geo__c:Go_Kart_Flag__c}
            FROM {Route_Sales_Geo__c}
        `,
        f: ['Default_Start_Time__c', 'Default_Starting_Location__c', 'Id', 'SLS_UNIT_NM__c', 'Go_Kart_Flag__c']
    },
    retrieveVisitDetailsData: {
        q: VisitDetailsQuery,
        f: VisitDetailsField
    },
    retrieveUnassignedEE: {
        q: UnassignedEEQuery,
        f: UnassignedEEField
    },
    updateVisitForDelete: {
        q: updateVisitForDeleteQuery,
        f: updateVisitForDeleteFields
    }
}

export default ScheduleQuery
