export interface StoreProduct {
    Id: string
    OwnerId: string
    IsDeleted: boolean
    Name: string
    RecordTypeId: string
    Createdstring: string
    CreatedById: string
    LastModifiedstring: string
    LastModifiedById: string
    SystemModstamp: string
    LastViewedstring: string
    Laststringdstring: string
    ProductId: string
    InStoreLocationId: string
    RetailStoreId: string
    AccountId: string
    Startstring: string
    Endstring: string
    IsFavorite: boolean
    DefaultOrderQuantity: string
    DisplayOrder: string
    DisplayQuantity: string
    Packaging: string
    DisplayItemId: string
    DeleteFlag: boolean
    FlavorName: string
    Status: string
    SPUniqueID: string
    AuthFlag: boolean
    ProductAvailability: boolean
    SubBrand: string
    ManstringdSell: boolean
    YTDLCDVol: string
    Authstring: string
    LOCPRODID: string
    No12LCWVoid: boolean
    No11WTDVoid: boolean
    RouteSalesGeo: string
    BURPTID: string
    CHTDCYMEASACTLQTY: string
    CHTDLCMCYMEASACTLQTY: string
    CHTDLCMPYMEASACTLQTY: string
    CHTDPYMEASACTLQTY: string
    CLCHCYMEASACTLQTY: string
    CLCHPYMEASACTLQTY: string
    CLCMCYMEASACTLQTY: string
    CLCMPYMEASACTLQTY: string
    CLCQCYMEASACTLQTY: string
    CLCQPYMEASACTLQTY: string
    CMTDCYMEASACTLQTY: string
    CMTDPYMEASACTLQTY: string
    CQTDCYMEASACTLQTY: string
    CQTDLCMCYMEASACTLQTY: string
    CQTDLCMPYMEASACTLQTY: string
    CQTDPYMEASACTLQTY: string
    CUSTID: string
    CYTDCYMEASACTLQTY: string
    CYTDLCMCYMEASACTLQTY: string
    CYTDLCMPYMEASACTLQTY: string
    CYTDPYMEASACTLQTY: string
    DELYMEASCDE: string
    INVENID: string
    LCDCYMEASACTLQTY: string
    LCDDTE: string
    LCDPYMEASACTLQTY: string
    LCPCYMEASACTLQTY: string
    LCPPYMEASACTLQTY: string
    LCQCYMEASACTLQTY: string
    LCQPYMEASACTLQTY: string
    LCWCYMEASACTLQTY: string
    LCWPYMEASACTLQTY: string
    MNTH10CYMEASACTLQTY: string
    MNTH10PYMEASACTLQTY: string
    MNTH11CYMEASACTLQTY: string
    MNTH11PYMEASACTLQTY: string
    MNTH12CYMEASACTLQTY: string
    MNTH12PYMEASACTLQTY: string
    MNTH1CYMEASACTLQTY: string
    MNTH1PYMEASACTLQTY: string
    MNTH2CYMEASACTLQTY: string
    MNTH2PYMEASACTLQTY: string
    MNTH3CYMEASACTLQTY: string
    MNTH3PYMEASACTLQTY: string
    MNTH4CYMEASACTLQTY: string
    MNTH4PYMEASACTLQTY: string
    MNTH5CYMEASACTLQTY: string
    MNTH5PYMEASACTLQTY: string
    MNTH6CYMEASACTLQTY: string
    MNTH6PYMEASACTLQTY: string
    MNTH7CYMEASACTLQTY: string
    MNTH7PYMEASACTLQTY: string
    MNTH8CYMEASACTLQTY: string
    MNTH8PYMEASACTLQTY: string
    MNTH9CYMEASACTLQTY: string
    MNTH9PYMEASACTLQTY: string
    PD10CYMEASACTLQTY: string
    PD10PYMEASACTLQTY: string
    PD11CYMEASACTLQTY: string
    PD11PYMEASACTLQTY: string
    PD12CYMEASACTLQTY: string
    PD12PYMEASACTLQTY: string
    PD13CYMEASACTLQTY: string
    PD13PYMEASACTLQTY: string
    PD1CQTRCYMEASACTLQTY: string
    PD1CQTRPYMEASACTLQTY: string
    PD1CYMEASACTLQTY: string
    PD1PYMEASACTLQTY: string
    PD2CQTRCYMEASACTLQTY: string
    PD2CQTRPYMEASACTLQTY: string
    PD2CYMEASACTLQTY: string
    PD2PYMEASACTLQTY: string
    PD3CQTRCYMEASACTLQTY: string
    PD3CQTRPYMEASACTLQTY: string
    PD3CYMEASACTLQTY: string
    PD3PYMEASACTLQTY: string
    PD4CQTRCYMEASACTLQTY: string
    PD4CQTRPYMEASACTLQTY: string
    PD4CYMEASACTLQTY: string
    PD4PYMEASACTLQTY: string
    PD5CYMEASACTLQTY: string
    PD5PYMEASACTLQTY: string
    PD6CYMEASACTLQTY: string
    PD6PYMEASACTLQTY: string
    PD7CYMEASACTLQTY: string
    PD7PYMEASACTLQTY: string
    PD8CYMEASACTLQTY: string
    PD8PYMEASACTLQTY: string
    PD9CYMEASACTLQTY: string
    PD9PYMEASACTLQTY: string
    PTDCYMEASACTLQTY: string
    PTDPYMEASACTLQTY: string
    QTDCYMEASACTLQTY: string
    QTDLCPCYMEASACTLQTY: string
    QTDLCPPYMEASACTLQTY: string
    QTDPYMEASACTLQTY: string
    QTR1CYMEASACTLQTY: string
    QTR1PYMEASACTLQTY: string
    QTR2CYMEASACTLQTY: string
    QTR2PYMEASACTLQTY: string
    QTR3CYMEASACTLQTY: string
    QTR3PYMEASACTLQTY: string
    QTR4CYMEASACTLQTY: string
    QTR4PYMEASACTLQTY: string
    RTEID: string
    WTDCYMEASACTLQTY: string
    WTDPYMEASACTLQTY: string
    YRDAYNUM: string
    YRNUM: string
    YRPDNUM: string
    YRQTRNUM: string
    YRWKNUM: string
    YTDCYMEASACTLQTY: string
    YTDLCPCYMEASACTLQTY: string
    YTDLCPPYMEASACTLQTY: string
    YTDPYMEASACTLQTY: string
    YTDNetRevenue: string
    stringOfNoSale: string
    stringOfWake: string
    Vol11WTD: string
    Vol12LCW: string
    OTSAuth: boolean
    IPScore: string
    OTSUpstringd: boolean
    YTDVolume: string
    CombinedAuthFlag: boolean
}
