export interface Visit {
    Id: string
    SalesVisit: string
    Name: string
    OwnerId: string
    PlaceId: string
    VisitorId: string
    VisitorName: string
    Status: string
    ActualEndTime: string
    ActualStartTime: string
    LastModifiedDate: string
    PlannedVisitEndTime: string
    PlannedVisitStartTime: string
    AdHoc: boolean
    RecordTypeId: string
    RecordTypeName: string
    RecordTypeDeveloperName: string
    PlannedDate: string
    Sequence: number
    VisitListId: string
    PlannedDurationMinutes: string
    ActualDurationMinutes: string
    PlannedTravelTime: number
    PlannedMileage: number
    ScheduledCaseQuantity: number
    VisitSubtype: string
    TakeOrderFlag: boolean
    AMASCompliant: boolean
    InstructionDescription: string
    CheckInLocationFlag: boolean
    PullNumber: number
    ManagerAdHoc: boolean
    CheckOutLocationFlag: boolean
    CustomerID: string
    CasesGoalQuantity: number
    RTE_ID: string
    RouteGroup: string
    ReassignedFlag: boolean
    DynamicFrequencyAdd: boolean
    DynamicFrequencyRemove: boolean
    Reassigned: boolean
    UserVisitList: string
    vlRefId: string
    userVlRefId: string
}
