/* eslint-disable camelcase */
import { BaseSoupInterface } from './SoupModel'

export interface Lead extends BaseSoupInterface {
    Action_Required_c__c: boolean
    Active_Base_Population_c__c: number
    Additional_Prospect_Comments_c__c: string
    Alcohol_c__c: string
    Annual_Sales_c__c: string
    BUSN_SGMNTTN_LVL_1_NM_c__c: string
    BUSN_SGMNTTN_LVL_2_NM_c__c: string
    BUSN_SGMNTTN_LVL_3_NM_c__c: string
    BUSN_SGMNTTN_LVL_4_NM_c__c: string
    BUSN_SGMNTTN_LVL_1_CDV_c__c: string
    BUSN_SGMNTTN_LVL_2_CDV_c__c: string
    BUSN_SGMNTTN_LVL_3_CDV_c__c: string
    BUSN_SGMNTTN_LVL_4_CDV_c__c: string
    Billing_Address_City_c__c: string
    Billing_Address_Country_c__c: string
    Billing_Address_Same_as_Shipping_c__c: string
    Billing_Address_State_c__c: string
    Billing_Address_Street_c__c: string
    Billing_Address_Zip_c__c: string
    Business_Type_c__c: string
    CMB_Notes_c__c: string
    COF_Rejected_c__c: string
    COF_Triggered_c__c: string
    Call_Counter_c__c: number
    Chain_Store_Number_c__c: string
    Chain_c__c: string
    City__c: string
    Company__c: string
    Contact_Made_Counter_c__c: number
    Country__c: string
    CreatedBy_GPID_c__c: string
    CreatedDate__c: string
    Current_Distributor_c__c: string
    Current_Price_BC_c__c: number
    Current_Price_FTN_c__c: number
    Customer_Number_c__c: string
    Customer_Type_c__c: string
    DUP_COF_c__c: string
    Days_Open_c__c: string
    Deferred_Resume_Date_c__c: string
    Delivery_Days_c__c: string
    Delivery_Frequency_c__c: string
    Delivery_Method_c__c: string
    Device_Source_c__c: string
    Email__c: string
    Estimated_BC_Volume_c__c: number
    Estimated_Coolers_c__c: number
    Estimated_FTN_Volume_c__c: number
    Estimated_Fountain_c__c: number
    Estimated_Other_Equip_c__c: number
    Estimated_Vendor_Volume_c__c: number
    Ethnicity_c__c: string
    ExternalId: string
    FF_LINK_c__c: string
    Friday_Delivery_End_c__c: string
    Friday_Delivery_Start_c__c: string
    Friday_End_Hours_of_Operation_c__c: string
    Friday_Start_Hours_of_Operation_c__c: string
    HQ_Address_City_c__c: string
    HQ_Address_Country_c__c: string
    HQ_Address_Postal_Code_c__c: string
    HQ_Address_State_c__c: string
    HQ_Address_Street_c__c: string
    HQ_Phone_c__c: string
    Id: string
    K_12_Enrollment_c__c: number
    LEAD_ID_c__c: string
    LastModifiedBy_GPID_c__c: string
    LastModifiedDate__c: string
    LastName__c: string
    Last_Task_Modified_Date_c__c: string
    LeadSource__c: string
    Lead_Sub_Status_c__c: string
    Lead_Type_c__c: string
    original_customer_c__c: string
    original_customer_number_c__c: string
    Lead_Unique_Id_c__c: string
    Location_c__c: string
    Location_ID_c__c: string
    Lodging_Catering_c__c: string
    Market_c__c: string
    Market_ID_c__c: string
    Monday_Delivery_End_c__c: string
    Monday_Delivery_Start_c__c: string
    Monday_End_Hours_of_Operation_c__c: string
    Monday_Start_Hours_of_Operation_c__c: string
    Moved_to_Negotiate_Time_c__c: string
    My_Lead_Action_Required_c__c: boolean
    Number_Units_c__c: string
    Number_of_Rooms_c__c: string
    Other_Equipment_Notes_c__c: string
    Other_Volume_c__c: number
    OwnerId__c: string
    Owner_GPID_c__c: string
    Owner_Name_c__c: string
    PD_Assigned_c__c: string
    PD_Call_Counter_c__c: number
    PD_Contact_Made_Counter_c__c: number
    POS_Needs_c__c: string
    Payment_Method_c__c: string
    Phone__c: string
    PostalCode__c: string
    Pre_Call_Comments_c__c: string
    Pre_Open_c__c: string
    Pre_qualified_c__c: string
    Primary_Language_c__c: string
    Product_Group_c__c: string
    Program_Offered_c__c: string
    Proposed_Key_Account_Division_c__c: string
    Proposed_Key_Account_c__c: string
    Proposed_Price_BC_c__c: number
    Proposed_Price_FTN_c__c: number
    Rating_c__c: number
    Rebates_BC_c__c: string
    Rebates_FTN_c__c: string
    Region_c__c: string
    Region_ID_c__c: string
    Rep_Last_Modified_Date_c__c: string
    Route_c__c: string
    Sales_Method_c__c: string
    Saturday_Delivery_End_c__c: string
    Saturday_Delivery_Start_c__c: string
    Saturday_End_Hours_of_Operation_c__c: string
    Saturday_Start_Hours_of_Operation_c__c: string
    Seasonal_Close_End_Date_c__c: string
    Seasonal_Close_Start_Date_c__c: string
    Secondary_Cuisine_c__c: string
    Send_for_COF_c__c: boolean
    Service_Location_c__c: string
    Source_ID_c__c: string
    Star_Level_c__c: number
    State__c: string
    Status__c: string
    Street__c: string
    Sunday_Delivery_End_c__c: string
    Sunday_Delivery_Start_c__c: string
    Sunday_End_Hours_of_Operation_c__c: string
    Sunday_Start_Hours_of_Operation_c__c: string
    Suggested_FSR_Nat_Route_Number_c__c: string
    Suggested_FSR_Loc_Route_Number_c__c: string
    Temp_Charge_c__c: string
    Thursday_Delivery_End_c__c: string
    Thursday_Delivery_Start_c__c: string
    Thursday_End_Hours_of_Operation_c__c: string
    Thursday_Start_Hours_of_Operation_c__c: string
    Tier_c__c: number
    Tuesday_Delivery_End_c__c: string
    Tuesday_Delivery_Start_c__c: string
    Tuesday_End_Hours_of_Operation_c__c: string
    Tuesday_Start_Hours_of_Operation_c__c: string
    User_Link_1_c__c: string
    User_Link_2_c__c: string
    User_Link_3_c__c: string
    User_Link_Label_1_c__c: string
    User_Link_Label_2_c__c: string
    User_Link_Label_3_c__c: string
    VENUES_ON_SITE_c__c: number
    Website__c: string
    Wednesday_Delivery_End_c__c: string
    Wednesday_Delivery_Start_c__c: string
    Wednesday_End_Hours_of_Operation_c__c: string
    Wednesday_Start_Hours_of_Operation_c__c: string
    YELP_HOT_AND_NEW_c__c: string
    Years_In_Business_c__c: string
    ff_DOORDASH_c__c: string
    ff_FACEBOOK_c__c: string
    ff_FOURSQUARE_c__c: string
    ff_GRUBHUB_c__c: string
    ff_MEAL_BREAKFAST_c__c: string
    ff_MEAL_DINNER_c__c: string
    ff_MEAL_LUNCH_c__c: string
    ff_MEAL_TAKEOUT_c__c: string
    ff_POSTMATES_c__c: string
    ff_UBEREATS_c__c: string
    ff_YELP_c__c: string
    gas_station_c__c: string
    Assigned_Date_c__c: string
    Business_Won_Date_c__c: string
    Customer_Submitted_Date_c__c: string
    Move_To_No_Sale_Date_c__c: string
    No_Go_Checkbox_c__c: boolean
    No_Go_Date_c__c: string
    No_Go_Reason_c__c: string
    Pre_Qualified_Contact_c__c: string
    Pre_Qualified_Time_c__c: string
}

export interface Task extends BaseSoupInterface {
    COF_Requested_Date__c: string
    Call_Date__c: string
    Call_Details__c: string
    Call_Details2__c: string
    Call_Details3__c: string
    Call_Subject__c: string
    Contact_Made__c: string
    CreatedDate: string
    Id: string
    Lead__c: string
    Name_of_Contact__c: string
    Onsite__c: string
    RecordTypeId: string
    Status: string
    Subject: string
    Type: string
    ActivityDate: string
    'CreatedBy.GPID__c': string
    Hotshot__c: string
}

export interface Contact extends BaseSoupInterface {
    CreatedDate: string
    Email: string
    FirstName: string
    Id: string
    LastName: string
    Lead__c: string
    MobilePhone: string
    Name: string
    Notes__c: string
    OwnerId: string
    Phone: string
    Preferred_Contact_Method__c: string
    Primary_Contact__c: string
    Primary_Phone_Extension__c: string
    Primary_Phone_Type__c: string
    Second_Phone_Extension__c: string
    Second_Phone_Type__c: string
    Secondary_Contact__c: string
    Title: string
}

// The naming following the Salesforce object.
// eslint-disable-next-line @typescript-eslint/naming-convention
export interface Customer_to_Route__c extends BaseSoupInterface {
    CUST_RTE_FREQ_CDE__c: string
    DELY_DAYS__c: string
    DELY_MTHD_CDE__c: string
    DLVRY_MTHD_NM__c: string
    Id: string
    Lead__c: string
    PROD_GRP_CDE__c: string
    PROD_GRP_NM__c: string
    RecordTypeId: string
    Route_Text__c: string
    SLS_MTHD_CDE__c: string
    SLS_MTHD_NM__c: string
}

export type LeadSoups = Lead | Task | Contact | Customer_to_Route__c
