/* eslint-disable camelcase */
import { BaseSoupInterface } from './SoupModel'

export interface Request extends BaseSoupInterface {
    Id: string
    Name: string
    std_attr_cde__c: string
    std_attr_cost__c: number
    slspad_attr_val__c: string
    attr_seq_num__c: string
    agent_cmnt_txt__c: string
    caller_name__c: string
    caller_phone_num__c: string
    canc_reas_cde__c: string
    canc_reas_cde_descri__c: string
    cets_extrnl_incdnt_id__c: string
    cets_ord_lne_num__c: string
    cets_ord_stat_cde__c: string
    comments__c: string
    Ctrct_cost_amt__c: number
    email_addr_txt__c: string
    customer_id__c: string
    svc_dsptch_note_txt__c: string
    display_in_asset_tab__c: boolean
    display_in_service_tab__c: boolean
    equip_config_type_cde__c: string
    equip_grphc_desc__c: string
    equip_grphc_id__c: string
    ident_item_id__c: string
    make_mdl_nme__c: string
    equip_mech_rte_amt__c: number
    equip_move_stat_cde__c: string
    equip_move_type_cde__c: string
    equip_move_type_desc__c: string
    ident_asset_num__c: string
    equip_serial_num__c: string
    equip_setup_desc__c: string
    equip_site_desc__c: string
    equip_site_srvy_id__c: string
    Equip_styp_cde__c: string
    equip_styp_desc__c: string
    Equip_type_cde__c: string
    equip_type_desc__c: string
    error_msg__c: string
    inven_id__c: string
    inven_label__c: string
    loc_nme__c: string
    Mnth_pymt_amt__c: number
    loc_move_id__c: string
    move_purpose_cde__c: string
    order_id__c: string
    Cmnt_txt__c: string
    order_line_num__c: string
    ord_lne_rel_num__c: string
    loc_prod_id__c: string
    Rent_bill_cde__c: string
    request_gpid__c: string
    requester_name__c: string
    requester_phone_num__c: string
    Sls_plan_cde__c: string
    slct_num__c: string
    Send_to_CETS__c: boolean
    Serv_bill_cde__c: string
    Serv_ctrct_id__c: string
    serv_ord_stat_cde__c: string
    serv_ord_type_cde__c: string
    svc_srce_cde__c: string
    std_setup_equip_id__c: string
    survey_response__c: string
    tech_cmnt_txt__c: string
    trbl_type_cde__c: string
    trbl_type_desc__c: string
}
